// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: dydxprotocol/lending/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// MsgCreateLendingAccount is a message used to create a new lending account.
type MsgCreateLendingAccount struct {
	// The address of the account creator.
	Creator string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
}

func (m *MsgCreateLendingAccount) Reset()         { *m = MsgCreateLendingAccount{} }
func (m *MsgCreateLendingAccount) String() string { return proto.CompactTextString(m) }
func (*MsgCreateLendingAccount) ProtoMessage()    {}
func (*MsgCreateLendingAccount) Descriptor() ([]byte, []int) {
	return fileDescriptor_5e283aa96acdc197, []int{0}
}
func (m *MsgCreateLendingAccount) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCreateLendingAccount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCreateLendingAccount.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCreateLendingAccount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateLendingAccount.Merge(m, src)
}
func (m *MsgCreateLendingAccount) XXX_Size() int {
	return m.Size()
}
func (m *MsgCreateLendingAccount) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateLendingAccount.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateLendingAccount proto.InternalMessageInfo

func (m *MsgCreateLendingAccount) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

// MsgCreateLendingAccountResponse defines the CreateLendingAccount response type.
type MsgCreateLendingAccountResponse struct {
}

func (m *MsgCreateLendingAccountResponse) Reset()         { *m = MsgCreateLendingAccountResponse{} }
func (m *MsgCreateLendingAccountResponse) String() string { return proto.CompactTextString(m) }
func (*MsgCreateLendingAccountResponse) ProtoMessage()    {}
func (*MsgCreateLendingAccountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5e283aa96acdc197, []int{1}
}
func (m *MsgCreateLendingAccountResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCreateLendingAccountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCreateLendingAccountResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCreateLendingAccountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateLendingAccountResponse.Merge(m, src)
}
func (m *MsgCreateLendingAccountResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgCreateLendingAccountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateLendingAccountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateLendingAccountResponse proto.InternalMessageInfo

// MsgCreateLendingPosition is a message used to open a new lending position.
type MsgCreateLendingPosition struct {
	// The address of the account owner.
	Creator string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	// The amount to be deposited.
	Amount types.Coin `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount"`
}

func (m *MsgCreateLendingPosition) Reset()         { *m = MsgCreateLendingPosition{} }
func (m *MsgCreateLendingPosition) String() string { return proto.CompactTextString(m) }
func (*MsgCreateLendingPosition) ProtoMessage()    {}
func (*MsgCreateLendingPosition) Descriptor() ([]byte, []int) {
	return fileDescriptor_5e283aa96acdc197, []int{2}
}
func (m *MsgCreateLendingPosition) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCreateLendingPosition) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCreateLendingPosition.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCreateLendingPosition) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateLendingPosition.Merge(m, src)
}
func (m *MsgCreateLendingPosition) XXX_Size() int {
	return m.Size()
}
func (m *MsgCreateLendingPosition) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateLendingPosition.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateLendingPosition proto.InternalMessageInfo

func (m *MsgCreateLendingPosition) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgCreateLendingPosition) GetAmount() types.Coin {
	if m != nil {
		return m.Amount
	}
	return types.Coin{}
}

// MsgCreateLendingPositionResponse defines the CreateLendingPosition response type.
type MsgCreateLendingPositionResponse struct {
}

func (m *MsgCreateLendingPositionResponse) Reset()         { *m = MsgCreateLendingPositionResponse{} }
func (m *MsgCreateLendingPositionResponse) String() string { return proto.CompactTextString(m) }
func (*MsgCreateLendingPositionResponse) ProtoMessage()    {}
func (*MsgCreateLendingPositionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5e283aa96acdc197, []int{3}
}
func (m *MsgCreateLendingPositionResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCreateLendingPositionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCreateLendingPositionResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCreateLendingPositionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateLendingPositionResponse.Merge(m, src)
}
func (m *MsgCreateLendingPositionResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgCreateLendingPositionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateLendingPositionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateLendingPositionResponse proto.InternalMessageInfo

// MsgUpdateLendingPosition is a message used to update an existing lending position.
type MsgUpdateLendingPosition struct {
	// The address of the account owner.
	Creator string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	// The ID of the position to update.
	PositionId string `protobuf:"bytes,2,opt,name=position_id,json=positionId,proto3" json:"position_id,omitempty"`
	// The asset to be added.
	Asset types.Coin `protobuf:"bytes,3,opt,name=asset,proto3" json:"asset"`
}

func (m *MsgUpdateLendingPosition) Reset()         { *m = MsgUpdateLendingPosition{} }
func (m *MsgUpdateLendingPosition) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateLendingPosition) ProtoMessage()    {}
func (*MsgUpdateLendingPosition) Descriptor() ([]byte, []int) {
	return fileDescriptor_5e283aa96acdc197, []int{4}
}
func (m *MsgUpdateLendingPosition) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateLendingPosition) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateLendingPosition.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateLendingPosition) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateLendingPosition.Merge(m, src)
}
func (m *MsgUpdateLendingPosition) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateLendingPosition) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateLendingPosition.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateLendingPosition proto.InternalMessageInfo

func (m *MsgUpdateLendingPosition) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgUpdateLendingPosition) GetPositionId() string {
	if m != nil {
		return m.PositionId
	}
	return ""
}

func (m *MsgUpdateLendingPosition) GetAsset() types.Coin {
	if m != nil {
		return m.Asset
	}
	return types.Coin{}
}

// MsgUpdateLendingPositionResponse defines the UpdateLendingPosition response type.
type MsgUpdateLendingPositionResponse struct {
}

func (m *MsgUpdateLendingPositionResponse) Reset()         { *m = MsgUpdateLendingPositionResponse{} }
func (m *MsgUpdateLendingPositionResponse) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateLendingPositionResponse) ProtoMessage()    {}
func (*MsgUpdateLendingPositionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5e283aa96acdc197, []int{5}
}
func (m *MsgUpdateLendingPositionResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateLendingPositionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateLendingPositionResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateLendingPositionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateLendingPositionResponse.Merge(m, src)
}
func (m *MsgUpdateLendingPositionResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateLendingPositionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateLendingPositionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateLendingPositionResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgCreateLendingAccount)(nil), "dydxprotocol.lending.MsgCreateLendingAccount")
	proto.RegisterType((*MsgCreateLendingAccountResponse)(nil), "dydxprotocol.lending.MsgCreateLendingAccountResponse")
	proto.RegisterType((*MsgCreateLendingPosition)(nil), "dydxprotocol.lending.MsgCreateLendingPosition")
	proto.RegisterType((*MsgCreateLendingPositionResponse)(nil), "dydxprotocol.lending.MsgCreateLendingPositionResponse")
	proto.RegisterType((*MsgUpdateLendingPosition)(nil), "dydxprotocol.lending.MsgUpdateLendingPosition")
	proto.RegisterType((*MsgUpdateLendingPositionResponse)(nil), "dydxprotocol.lending.MsgUpdateLendingPositionResponse")
}

func init() { proto.RegisterFile("dydxprotocol/lending/tx.proto", fileDescriptor_5e283aa96acdc197) }

var fileDescriptor_5e283aa96acdc197 = []byte{
	// 472 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x94, 0x41, 0x6b, 0x14, 0x31,
	0x14, 0xc7, 0x37, 0xae, 0xad, 0x34, 0xf5, 0x34, 0xac, 0x74, 0x3a, 0xe0, 0xec, 0xba, 0xa7, 0x52,
	0xd8, 0x84, 0x5d, 0xa9, 0x82, 0xb7, 0x6e, 0x41, 0x11, 0x2c, 0x94, 0x2d, 0x5e, 0xf4, 0x50, 0x32,
	0x49, 0x48, 0x03, 0x9d, 0x64, 0x98, 0xa4, 0x65, 0x0b, 0x82, 0xe2, 0xd9, 0x83, 0x17, 0xbf, 0x47,
	0x0f, 0xfd, 0x10, 0x3d, 0x16, 0x4f, 0x9e, 0x44, 0x76, 0x0f, 0xfd, 0x1a, 0x32, 0x93, 0x4c, 0x2d,
	0x65, 0xa6, 0xb4, 0xd2, 0xd3, 0x4c, 0xde, 0xff, 0x9f, 0xe4, 0xf7, 0xf2, 0x1e, 0x0f, 0x3e, 0x65,
	0xc7, 0x6c, 0x9a, 0xe5, 0xda, 0x6a, 0xaa, 0x0f, 0xf0, 0x01, 0x57, 0x4c, 0x2a, 0x81, 0xed, 0x14,
	0x95, 0xb1, 0xa0, 0x73, 0x55, 0x46, 0x5e, 0x8e, 0x56, 0xa9, 0x36, 0xa9, 0x36, 0x7b, 0xa5, 0x80,
	0xdd, 0xc2, 0x6d, 0x88, 0x56, 0xdc, 0x0a, 0xa7, 0x46, 0xe0, 0xa3, 0x61, 0xf1, 0xf1, 0x42, 0x47,
	0x68, 0xa1, 0xdd, 0x86, 0xe2, 0xcf, 0x47, 0x63, 0x6f, 0x4f, 0x88, 0xe1, 0xf8, 0x68, 0x98, 0x70,
	0x4b, 0x86, 0x98, 0x6a, 0xa9, 0x9c, 0xde, 0xff, 0x08, 0x57, 0xb6, 0x8d, 0xd8, 0xca, 0x39, 0xb1,
	0xfc, 0x9d, 0xbb, 0x7d, 0x93, 0x52, 0x7d, 0xa8, 0x6c, 0x30, 0x82, 0x8f, 0x68, 0x11, 0xd7, 0x79,
	0x08, 0x7a, 0x60, 0x6d, 0x69, 0x1c, 0xfe, 0x3c, 0x1d, 0x74, 0x3c, 0xcc, 0x26, 0x63, 0x39, 0x37,
	0x66, 0xd7, 0xe6, 0x52, 0x89, 0x49, 0x65, 0x7c, 0xf5, 0xf8, 0xeb, 0xc5, 0xc9, 0x7a, 0xb5, 0xea,
	0x3f, 0x83, 0xdd, 0x86, 0xc3, 0x27, 0xdc, 0x64, 0x5a, 0x19, 0xde, 0xff, 0x01, 0x60, 0x78, 0xdd,
	0xb3, 0xa3, 0x8d, 0xb4, 0x52, 0xab, 0xff, 0x21, 0x08, 0x5e, 0xc2, 0x45, 0x92, 0x16, 0x57, 0x84,
	0x0f, 0x7a, 0x60, 0x6d, 0x79, 0xb4, 0x8a, 0xbc, 0xbf, 0x78, 0x01, 0xe4, 0x5f, 0x00, 0x6d, 0x69,
	0xa9, 0xc6, 0x0f, 0xcf, 0x7e, 0x77, 0x5b, 0x13, 0x6f, 0xbf, 0x86, 0xde, 0x87, 0xbd, 0x26, 0xac,
	0x4b, 0xf6, 0x53, 0xc7, 0xfe, 0x3e, 0x63, 0xf7, 0xc4, 0xde, 0x85, 0xcb, 0x99, 0xdf, 0xbf, 0x27,
	0x59, 0x99, 0xc0, 0xd2, 0x04, 0x56, 0xa1, 0xb7, 0x2c, 0xd8, 0x80, 0x0b, 0xc4, 0x18, 0x6e, 0xc3,
	0xf6, 0xed, 0x72, 0x73, 0xee, 0xda, 0xd4, 0x6a, 0xa9, 0xab, 0xd4, 0x46, 0xdf, 0xda, 0xb0, 0xbd,
	0x6d, 0x44, 0xf0, 0x09, 0x76, 0x6a, 0x7b, 0x63, 0x80, 0xea, 0xfa, 0x16, 0x35, 0x54, 0x3b, 0xda,
	0xb8, 0x93, 0xbd, 0xa2, 0x08, 0x3e, 0xc3, 0x27, 0xf5, 0x8d, 0x81, 0x6e, 0x77, 0x5e, 0xe5, 0x8f,
	0x5e, 0xdc, 0xcd, 0x7f, 0x15, 0xa0, 0xbe, 0xba, 0xcd, 0x00, 0xb5, 0xfe, 0x1b, 0x00, 0x6e, 0xac,
	0x43, 0xb4, 0xf0, 0xe5, 0xe2, 0x64, 0x1d, 0x8c, 0xc9, 0xd9, 0x2c, 0x06, 0xe7, 0xb3, 0x18, 0xfc,
	0x99, 0xc5, 0xe0, 0xfb, 0x3c, 0x6e, 0x9d, 0xcf, 0xe3, 0xd6, 0xaf, 0x79, 0xdc, 0xfa, 0xf0, 0x46,
	0x48, 0xbb, 0x7f, 0x98, 0x20, 0xaa, 0x53, 0xbc, 0x6b, 0x73, 0x4e, 0xd2, 0xd7, 0x52, 0x11, 0x45,
	0xf9, 0x60, 0xa7, 0x9a, 0x39, 0xa6, 0x0c, 0x0f, 0xe8, 0x3e, 0x91, 0x0a, 0x5f, 0x4e, 0xa2, 0xe9,
	0xbf, 0x59, 0x74, 0x9c, 0x71, 0x93, 0x2c, 0x96, 0xca, 0xf3, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff,
	0xa1, 0x0d, 0x5d, 0xcf, 0xb0, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	// CreateLendingAccount creates a new lending account.
	CreateLendingAccount(ctx context.Context, in *MsgCreateLendingAccount, opts ...grpc.CallOption) (*MsgCreateLendingAccountResponse, error)
	// CreateLendingPosition opens a new lending position.
	CreateLendingPosition(ctx context.Context, in *MsgCreateLendingPosition, opts ...grpc.CallOption) (*MsgCreateLendingPositionResponse, error)
	// UpdateLendingPosition updates an existing lending position.
	UpdateLendingPosition(ctx context.Context, in *MsgUpdateLendingPosition, opts ...grpc.CallOption) (*MsgUpdateLendingPositionResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) CreateLendingAccount(ctx context.Context, in *MsgCreateLendingAccount, opts ...grpc.CallOption) (*MsgCreateLendingAccountResponse, error) {
	out := new(MsgCreateLendingAccountResponse)
	err := c.cc.Invoke(ctx, "/dydxprotocol.lending.Msg/CreateLendingAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) CreateLendingPosition(ctx context.Context, in *MsgCreateLendingPosition, opts ...grpc.CallOption) (*MsgCreateLendingPositionResponse, error) {
	out := new(MsgCreateLendingPositionResponse)
	err := c.cc.Invoke(ctx, "/dydxprotocol.lending.Msg/CreateLendingPosition", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) UpdateLendingPosition(ctx context.Context, in *MsgUpdateLendingPosition, opts ...grpc.CallOption) (*MsgUpdateLendingPositionResponse, error) {
	out := new(MsgUpdateLendingPositionResponse)
	err := c.cc.Invoke(ctx, "/dydxprotocol.lending.Msg/UpdateLendingPosition", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	// CreateLendingAccount creates a new lending account.
	CreateLendingAccount(context.Context, *MsgCreateLendingAccount) (*MsgCreateLendingAccountResponse, error)
	// CreateLendingPosition opens a new lending position.
	CreateLendingPosition(context.Context, *MsgCreateLendingPosition) (*MsgCreateLendingPositionResponse, error)
	// UpdateLendingPosition updates an existing lending position.
	UpdateLendingPosition(context.Context, *MsgUpdateLendingPosition) (*MsgUpdateLendingPositionResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) CreateLendingAccount(ctx context.Context, req *MsgCreateLendingAccount) (*MsgCreateLendingAccountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateLendingAccount not implemented")
}
func (*UnimplementedMsgServer) CreateLendingPosition(ctx context.Context, req *MsgCreateLendingPosition) (*MsgCreateLendingPositionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateLendingPosition not implemented")
}
func (*UnimplementedMsgServer) UpdateLendingPosition(ctx context.Context, req *MsgUpdateLendingPosition) (*MsgUpdateLendingPositionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateLendingPosition not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_CreateLendingAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgCreateLendingAccount)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).CreateLendingAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dydxprotocol.lending.Msg/CreateLendingAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).CreateLendingAccount(ctx, req.(*MsgCreateLendingAccount))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_CreateLendingPosition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgCreateLendingPosition)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).CreateLendingPosition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dydxprotocol.lending.Msg/CreateLendingPosition",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).CreateLendingPosition(ctx, req.(*MsgCreateLendingPosition))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_UpdateLendingPosition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateLendingPosition)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateLendingPosition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dydxprotocol.lending.Msg/UpdateLendingPosition",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateLendingPosition(ctx, req.(*MsgUpdateLendingPosition))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "dydxprotocol.lending.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateLendingAccount",
			Handler:    _Msg_CreateLendingAccount_Handler,
		},
		{
			MethodName: "CreateLendingPosition",
			Handler:    _Msg_CreateLendingPosition_Handler,
		},
		{
			MethodName: "UpdateLendingPosition",
			Handler:    _Msg_UpdateLendingPosition_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dydxprotocol/lending/tx.proto",
}

func (m *MsgCreateLendingAccount) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCreateLendingAccount) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCreateLendingAccount) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgCreateLendingAccountResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCreateLendingAccountResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCreateLendingAccountResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgCreateLendingPosition) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCreateLendingPosition) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCreateLendingPosition) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Amount.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgCreateLendingPositionResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCreateLendingPositionResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCreateLendingPositionResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgUpdateLendingPosition) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateLendingPosition) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateLendingPosition) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Asset.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	if len(m.PositionId) > 0 {
		i -= len(m.PositionId)
		copy(dAtA[i:], m.PositionId)
		i = encodeVarintTx(dAtA, i, uint64(len(m.PositionId)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgUpdateLendingPositionResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateLendingPositionResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateLendingPositionResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgCreateLendingAccount) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgCreateLendingAccountResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgCreateLendingPosition) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = m.Amount.Size()
	n += 1 + l + sovTx(uint64(l))
	return n
}

func (m *MsgCreateLendingPositionResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgUpdateLendingPosition) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.PositionId)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = m.Asset.Size()
	n += 1 + l + sovTx(uint64(l))
	return n
}

func (m *MsgUpdateLendingPositionResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgCreateLendingAccount) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCreateLendingAccount: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCreateLendingAccount: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCreateLendingAccountResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCreateLendingAccountResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCreateLendingAccountResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCreateLendingPosition) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCreateLendingPosition: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCreateLendingPosition: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Amount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCreateLendingPositionResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCreateLendingPositionResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCreateLendingPositionResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateLendingPosition) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateLendingPosition: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateLendingPosition: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PositionId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PositionId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Asset", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Asset.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateLendingPositionResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateLendingPositionResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateLendingPositionResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
