package constants

import (
	"math/big"

	dtypes "github.com/StreamFinance-Protocol/stream-chain/protocol/dtypes"
)

var (
	NegativeTenQuantumsBigInt                        = big.NewInt(-10)
	NegativeTenQuantumsSerializableInt               = dtypes.NewIntFromString("-10")
	ZeroQuantumsBigInt                               = big.NewInt(0)
	ZeroQuantumsSerializableInt                      = dtypes.NewIntFromString("0")
	OneQuantumBigInt                                 = big.NewInt(1)
	OneQuantumSerializableInt                        = dtypes.NewIntFromString("1")
	FiveQuantumsBigInt                               = big.NewInt(5)
	FiveQuantumsSerializableInt                      = dtypes.NewIntFromString("5")
	NineQuantumsBigInt                               = big.NewInt(9)
	NineQuantumsSerializableInt                      = dtypes.NewIntFromString("9")
	TenQuantumsBigInt                                = big.NewInt(10)
	TenQuantumsSerializableInt                       = dtypes.NewIntFromString("10")
	FifteenQuantumsBigInt                            = big.NewInt(15)
	FifteenQuantumsSerializableInt                   = dtypes.NewIntFromString("15")
	NineteenQuantumsBigInt                           = big.NewInt(19)
	NineteenQuantumsSerializableInt                  = dtypes.NewIntFromString("19")
	TwentyQuantumsBigInt                             = big.NewInt(20)
	TwentyQuantumsSerializableInt                    = dtypes.NewIntFromString("20")
	TwentyFiveQuantumsBigInt                         = big.NewInt(25)
	TwentyFiveQuantumsSerializableInt                = dtypes.NewIntFromString("25")
	ThirtyQuantumsBigInt                             = big.NewInt(30)
	ThirtyQuantumsSerializableInt                    = dtypes.NewIntFromString("30")
	FourtyQuantumsBigInt                             = big.NewInt(40)
	FourtyQuantumsSerializableInt                    = dtypes.NewIntFromString("40")
	OneHundredQuantumsBigInt                         = big.NewInt(100)
	OneHundredQuantumsSerializableInt                = dtypes.NewIntFromString("100")
	OneThousandQuantumsBigInt                        = big.NewInt(1_000)
	OneThousandQuantumsSerializableInt               = dtypes.NewIntFromString("1_000")
	TenMillionQuantumsBigInt                         = big.NewInt(10_000_000)
	TenMillionQuantumsSerializableInt                = dtypes.NewIntFromString("10_000_000")
	TwentyFiveMillionQuantumsBigInt                  = big.NewInt(25_000_000)
	TwentyFiveMillionQuantumsSerializableInt         = dtypes.NewIntFromString("25_000_000")
	FiftyMillionQuantumsBigInt                       = big.NewInt(50_000_000)
	FiftyMillionQuantumsSerializableInt              = dtypes.NewIntFromString("50_000_000")
	SeventyFiveMillionQuantumsBigInt                 = big.NewInt(75_000_000)
	SeventyFiveMillionQuantumsSerializableInt        = dtypes.NewIntFromString("75_000_000")
	OneHundredMillionQuantumsBigInt                  = big.NewInt(100_000_000)
	OneHundredMillionQuantumsSerializableInt         = dtypes.NewIntFromString("100_000_000")
	OneHundredAndFiftyMillionQuantumsBigInt          = big.NewInt(150_000_000)
	OneHundredAndFiftyMillionQuantumsSerializableInt = dtypes.NewIntFromString("150_000_000")
	OneBillionQuantumsBigInt                         = big.NewInt(1_000_000_000)
	OneBillionQuantumsSerializableInt                = dtypes.NewIntFromString("1_000_000_000")
	TenBillionQuantumsBigInt                         = big.NewInt(10_000_000_000)
	TenBillionQuantumsSerializableInt                = dtypes.NewIntFromString("10_000_000_000")
)
