// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: dydxprotocol/sending/transfer.proto

package types

import (
	fmt "fmt"
	github_com_StreamFinance_Protocol_stream_chain_protocol_dtypes "github.com/StreamFinance-Protocol/stream-chain/protocol/dtypes"
	types "github.com/StreamFinance-Protocol/stream-chain/protocol/x/subaccounts/types"
	_ "github.com/cosmos/cosmos-proto"
	types1 "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Transfer represents a single transfer between two subaccounts.
type Transfer struct {
	// The sender subaccount ID.
	Sender types.SubaccountId `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender"`
	// The recipient subaccount ID.
	Recipient types.SubaccountId `protobuf:"bytes,2,opt,name=recipient,proto3" json:"recipient"`
	// Id of the asset to transfer.
	AssetId uint32 `protobuf:"varint,3,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	// The amount of asset to transfer
	Amount github_com_StreamFinance_Protocol_stream_chain_protocol_dtypes.SerializableInt `protobuf:"bytes,4,opt,name=amount,proto3,customtype=github.com/StreamFinance-Protocol/stream-chain/protocol/dtypes.SerializableInt" json:"amount"`
}

func (m *Transfer) Reset()         { *m = Transfer{} }
func (m *Transfer) String() string { return proto.CompactTextString(m) }
func (*Transfer) ProtoMessage()    {}
func (*Transfer) Descriptor() ([]byte, []int) {
	return fileDescriptor_6ef1d018df19de71, []int{0}
}
func (m *Transfer) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Transfer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Transfer.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Transfer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transfer.Merge(m, src)
}
func (m *Transfer) XXX_Size() int {
	return m.Size()
}
func (m *Transfer) XXX_DiscardUnknown() {
	xxx_messageInfo_Transfer.DiscardUnknown(m)
}

var xxx_messageInfo_Transfer proto.InternalMessageInfo

func (m *Transfer) GetSender() types.SubaccountId {
	if m != nil {
		return m.Sender
	}
	return types.SubaccountId{}
}

func (m *Transfer) GetRecipient() types.SubaccountId {
	if m != nil {
		return m.Recipient
	}
	return types.SubaccountId{}
}

func (m *Transfer) GetAssetId() uint32 {
	if m != nil {
		return m.AssetId
	}
	return 0
}

// MsgDepositToSubaccount represents a single transfer from an `x/bank`
// account to an `x/subaccounts` subaccount.
type MsgDepositToSubaccount struct {
	// The sender wallet address.
	Sender string `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	// The recipient subaccount ID.
	Recipient types.SubaccountId `protobuf:"bytes,2,opt,name=recipient,proto3" json:"recipient"`
	// Id of the asset to transfer.
	AssetId uint32 `protobuf:"varint,3,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	// The number of quantums of asset to transfer.
	Quantums github_com_StreamFinance_Protocol_stream_chain_protocol_dtypes.SerializableInt `protobuf:"bytes,4,opt,name=quantums,proto3,customtype=github.com/StreamFinance-Protocol/stream-chain/protocol/dtypes.SerializableInt" json:"quantums"`
}

func (m *MsgDepositToSubaccount) Reset()         { *m = MsgDepositToSubaccount{} }
func (m *MsgDepositToSubaccount) String() string { return proto.CompactTextString(m) }
func (*MsgDepositToSubaccount) ProtoMessage()    {}
func (*MsgDepositToSubaccount) Descriptor() ([]byte, []int) {
	return fileDescriptor_6ef1d018df19de71, []int{1}
}
func (m *MsgDepositToSubaccount) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgDepositToSubaccount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgDepositToSubaccount.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgDepositToSubaccount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgDepositToSubaccount.Merge(m, src)
}
func (m *MsgDepositToSubaccount) XXX_Size() int {
	return m.Size()
}
func (m *MsgDepositToSubaccount) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgDepositToSubaccount.DiscardUnknown(m)
}

var xxx_messageInfo_MsgDepositToSubaccount proto.InternalMessageInfo

func (m *MsgDepositToSubaccount) GetSender() string {
	if m != nil {
		return m.Sender
	}
	return ""
}

func (m *MsgDepositToSubaccount) GetRecipient() types.SubaccountId {
	if m != nil {
		return m.Recipient
	}
	return types.SubaccountId{}
}

func (m *MsgDepositToSubaccount) GetAssetId() uint32 {
	if m != nil {
		return m.AssetId
	}
	return 0
}

// MsgWithdrawFromSubaccount represents a single transfer from an
// `x/subaccounts` subaccount to an `x/bank` account.
type MsgWithdrawFromSubaccount struct {
	// The sender subaccount ID.
	Sender types.SubaccountId `protobuf:"bytes,2,opt,name=sender,proto3" json:"sender"`
	// The recipient wallet address.
	Recipient string `protobuf:"bytes,1,opt,name=recipient,proto3" json:"recipient,omitempty"`
	// Id of the asset to transfer.
	AssetId uint32 `protobuf:"varint,3,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	// The number of quantums of asset to transfer.
	Quantums github_com_StreamFinance_Protocol_stream_chain_protocol_dtypes.SerializableInt `protobuf:"bytes,4,opt,name=quantums,proto3,customtype=github.com/StreamFinance-Protocol/stream-chain/protocol/dtypes.SerializableInt" json:"quantums"`
}

func (m *MsgWithdrawFromSubaccount) Reset()         { *m = MsgWithdrawFromSubaccount{} }
func (m *MsgWithdrawFromSubaccount) String() string { return proto.CompactTextString(m) }
func (*MsgWithdrawFromSubaccount) ProtoMessage()    {}
func (*MsgWithdrawFromSubaccount) Descriptor() ([]byte, []int) {
	return fileDescriptor_6ef1d018df19de71, []int{2}
}
func (m *MsgWithdrawFromSubaccount) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgWithdrawFromSubaccount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgWithdrawFromSubaccount.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgWithdrawFromSubaccount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgWithdrawFromSubaccount.Merge(m, src)
}
func (m *MsgWithdrawFromSubaccount) XXX_Size() int {
	return m.Size()
}
func (m *MsgWithdrawFromSubaccount) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgWithdrawFromSubaccount.DiscardUnknown(m)
}

var xxx_messageInfo_MsgWithdrawFromSubaccount proto.InternalMessageInfo

func (m *MsgWithdrawFromSubaccount) GetSender() types.SubaccountId {
	if m != nil {
		return m.Sender
	}
	return types.SubaccountId{}
}

func (m *MsgWithdrawFromSubaccount) GetRecipient() string {
	if m != nil {
		return m.Recipient
	}
	return ""
}

func (m *MsgWithdrawFromSubaccount) GetAssetId() uint32 {
	if m != nil {
		return m.AssetId
	}
	return 0
}

// MsgSendFromModuleToAccount represents a single transfer from a module
// to an `x/bank` account (can be either a module account address or a user
// account address).
// Should only be executed by governance.
type MsgSendFromModuleToAccount struct {
	Authority string `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	// The sender module name.
	SenderModuleName string `protobuf:"bytes,2,opt,name=sender_module_name,json=senderModuleName,proto3" json:"sender_module_name,omitempty"`
	// The recipient account address (can be either a module account address
	// or a user account address).
	Recipient string `protobuf:"bytes,3,opt,name=recipient,proto3" json:"recipient,omitempty"`
	// The coin to transfer, which specifies both denom and amount.
	Coin types1.Coin `protobuf:"bytes,4,opt,name=coin,proto3" json:"coin"`
}

func (m *MsgSendFromModuleToAccount) Reset()         { *m = MsgSendFromModuleToAccount{} }
func (m *MsgSendFromModuleToAccount) String() string { return proto.CompactTextString(m) }
func (*MsgSendFromModuleToAccount) ProtoMessage()    {}
func (*MsgSendFromModuleToAccount) Descriptor() ([]byte, []int) {
	return fileDescriptor_6ef1d018df19de71, []int{3}
}
func (m *MsgSendFromModuleToAccount) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSendFromModuleToAccount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSendFromModuleToAccount.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSendFromModuleToAccount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSendFromModuleToAccount.Merge(m, src)
}
func (m *MsgSendFromModuleToAccount) XXX_Size() int {
	return m.Size()
}
func (m *MsgSendFromModuleToAccount) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSendFromModuleToAccount.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSendFromModuleToAccount proto.InternalMessageInfo

func (m *MsgSendFromModuleToAccount) GetAuthority() string {
	if m != nil {
		return m.Authority
	}
	return ""
}

func (m *MsgSendFromModuleToAccount) GetSenderModuleName() string {
	if m != nil {
		return m.SenderModuleName
	}
	return ""
}

func (m *MsgSendFromModuleToAccount) GetRecipient() string {
	if m != nil {
		return m.Recipient
	}
	return ""
}

func (m *MsgSendFromModuleToAccount) GetCoin() types1.Coin {
	if m != nil {
		return m.Coin
	}
	return types1.Coin{}
}

func init() {
	proto.RegisterType((*Transfer)(nil), "dydxprotocol.sending.Transfer")
	proto.RegisterType((*MsgDepositToSubaccount)(nil), "dydxprotocol.sending.MsgDepositToSubaccount")
	proto.RegisterType((*MsgWithdrawFromSubaccount)(nil), "dydxprotocol.sending.MsgWithdrawFromSubaccount")
	proto.RegisterType((*MsgSendFromModuleToAccount)(nil), "dydxprotocol.sending.MsgSendFromModuleToAccount")
}

func init() {
	proto.RegisterFile("dydxprotocol/sending/transfer.proto", fileDescriptor_6ef1d018df19de71)
}

var fileDescriptor_6ef1d018df19de71 = []byte{
	// 563 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xd4, 0x94, 0x4f, 0x6b, 0x13, 0x4f,
	0x18, 0xc7, 0xb3, 0x69, 0xc8, 0x2f, 0x99, 0xfc, 0x14, 0x59, 0x82, 0x26, 0x39, 0x6c, 0x43, 0x04,
	0x89, 0x62, 0x76, 0x4d, 0x0b, 0x3d, 0xf4, 0xd6, 0x58, 0x2a, 0x11, 0x52, 0x24, 0x09, 0x0a, 0x5e,
	0xc2, 0xec, 0xce, 0xb8, 0x19, 0xc8, 0xcc, 0xc4, 0x99, 0xd9, 0xda, 0x78, 0xf4, 0x15, 0xf8, 0x2e,
	0xbc, 0x8a, 0xe8, 0x7b, 0xe8, 0xb1, 0x78, 0x12, 0x0f, 0x45, 0x92, 0x83, 0x2f, 0x43, 0x99, 0xdd,
	0x61, 0x37, 0x39, 0x55, 0x2a, 0x0a, 0x9e, 0x76, 0x66, 0xbf, 0xcf, 0xdf, 0xcf, 0x33, 0x3c, 0xe0,
	0x36, 0x5a, 0xa0, 0xd3, 0xb9, 0xe0, 0x8a, 0x07, 0x7c, 0xe6, 0x49, 0xcc, 0x10, 0x61, 0xa1, 0xa7,
	0x04, 0x64, 0xf2, 0x05, 0x16, 0x6e, 0xac, 0xd8, 0xd5, 0x75, 0x23, 0xd7, 0x18, 0x35, 0xea, 0x01,
	0x97, 0x94, 0xcb, 0x49, 0x2c, 0x78, 0xc9, 0x25, 0x71, 0x68, 0x38, 0xc9, 0xcd, 0xf3, 0xa1, 0xc4,
	0xde, 0x49, 0xd7, 0xc7, 0x0a, 0x76, 0xbd, 0x80, 0x13, 0x66, 0xf4, 0x5b, 0x46, 0xa7, 0x32, 0xf4,
	0x4e, 0xba, 0xfa, 0x63, 0x84, 0x6a, 0xc8, 0x43, 0x9e, 0x04, 0xd4, 0x27, 0xf3, 0xf7, 0xee, 0x66,
	0x91, 0x91, 0x0f, 0x83, 0x80, 0x47, 0x4c, 0xc9, 0xb5, 0x73, 0x62, 0xda, 0x7a, 0x97, 0x07, 0xa5,
	0xb1, 0xa9, 0xde, 0x3e, 0x04, 0x45, 0x5d, 0x2c, 0x16, 0x35, 0xab, 0x69, 0xb5, 0x2b, 0x3b, 0x77,
	0xdc, 0xcd, 0x46, 0xb2, 0x40, 0xee, 0x28, 0x3d, 0xf7, 0x51, 0xaf, 0x70, 0x76, 0xb1, 0x9d, 0x1b,
	0x1a, 0x5f, 0xfb, 0x31, 0x28, 0x0b, 0x1c, 0x90, 0x39, 0xc1, 0x4c, 0xd5, 0xf2, 0x57, 0x08, 0x94,
	0xb9, 0xdb, 0x75, 0x50, 0x82, 0x52, 0x62, 0x35, 0x21, 0xa8, 0xb6, 0xd5, 0xb4, 0xda, 0xd7, 0x86,
	0xff, 0xc5, 0xf7, 0x3e, 0xb2, 0x19, 0x28, 0x42, 0xaa, 0xfd, 0x6a, 0x85, 0xa6, 0xd5, 0xfe, 0xbf,
	0xf7, 0x54, 0xfb, 0x7e, 0xbd, 0xd8, 0x3e, 0x0e, 0x89, 0x9a, 0x46, 0xbe, 0x1b, 0x70, 0xea, 0x8d,
	0x94, 0xc0, 0x90, 0x1e, 0x11, 0x06, 0x59, 0x80, 0x3b, 0x4f, 0x52, 0x22, 0xf1, 0xef, 0x4e, 0x30,
	0x85, 0x84, 0x79, 0x29, 0x27, 0xa4, 0x16, 0x73, 0x2c, 0xdd, 0x11, 0x16, 0x04, 0xce, 0xc8, 0x6b,
	0xe8, 0xcf, 0x70, 0x9f, 0xa9, 0xa1, 0xc9, 0xd2, 0xfa, 0x90, 0x07, 0x37, 0x07, 0x32, 0x3c, 0xc4,
	0x73, 0x2e, 0x89, 0x1a, 0xf3, 0xac, 0x70, 0xfb, 0xc1, 0x06, 0xb7, 0x72, 0xaf, 0xf6, 0xf9, 0x63,
	0xa7, 0x6a, 0x06, 0x7c, 0x80, 0x90, 0xc0, 0x52, 0x8e, 0x94, 0x20, 0x2c, 0xfc, 0xdb, 0x8c, 0x04,
	0x28, 0xbd, 0x8c, 0x20, 0x53, 0x11, 0x95, 0x7f, 0x98, 0x52, 0x9a, 0x67, 0xbf, 0xf2, 0xe6, 0xfb,
	0xfb, 0x7b, 0xa6, 0xcf, 0xd6, 0xa7, 0x3c, 0xa8, 0x0f, 0x64, 0xf8, 0x8c, 0xa8, 0x29, 0x12, 0xf0,
	0xd5, 0x91, 0xe0, 0x74, 0x8d, 0x5b, 0xf6, 0xde, 0xf2, 0xbf, 0xf1, 0xde, 0xf6, 0xd6, 0x59, 0x5e,
	0x36, 0x80, 0x7f, 0x84, 0xdb, 0x0f, 0x0b, 0x34, 0x06, 0x32, 0x1c, 0x61, 0x86, 0x34, 0xb3, 0x01,
	0x47, 0xd1, 0x0c, 0x8f, 0xf9, 0x81, 0x01, 0xb7, 0x07, 0xca, 0x30, 0x52, 0x53, 0x2e, 0x88, 0x5a,
	0x5c, 0xde, 0x72, 0x6a, 0x6a, 0xdf, 0x07, 0x76, 0x92, 0x60, 0x42, 0xe3, 0x88, 0x13, 0x06, 0x29,
	0x8e, 0xe1, 0x97, 0x87, 0x37, 0x12, 0x25, 0x49, 0x75, 0x0c, 0x29, 0xde, 0x04, 0xbb, 0xf5, 0xeb,
	0x60, 0x77, 0x41, 0x41, 0xef, 0xae, 0x98, 0x5c, 0x65, 0xa7, 0xee, 0x1a, 0x7b, 0xbd, 0xdc, 0x5c,
	0xb3, 0xdc, 0xdc, 0x87, 0x9c, 0x30, 0x33, 0xc7, 0xd8, 0x78, 0xff, 0xba, 0x6e, 0x3f, 0x2b, 0xb5,
	0x07, 0xcf, 0x96, 0x8e, 0x75, 0xbe, 0x74, 0xac, 0x6f, 0x4b, 0xc7, 0x7a, 0xbb, 0x72, 0x72, 0xe7,
	0x2b, 0x27, 0xf7, 0x65, 0xe5, 0xe4, 0x9e, 0x3f, 0xba, 0xea, 0x08, 0x4e, 0xb3, 0x7d, 0xad, 0x67,
	0xe1, 0x17, 0x63, 0x65, 0xf7, 0x67, 0x00, 0x00, 0x00, 0xff, 0xff, 0xd0, 0x70, 0x8d, 0xf8, 0xd4,
	0x05, 0x00, 0x00,
}

func (m *Transfer) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Transfer) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Transfer) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.Amount.Size()
		i -= size
		if _, err := m.Amount.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintTransfer(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	if m.AssetId != 0 {
		i = encodeVarintTransfer(dAtA, i, uint64(m.AssetId))
		i--
		dAtA[i] = 0x18
	}
	{
		size, err := m.Recipient.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTransfer(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	{
		size, err := m.Sender.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTransfer(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *MsgDepositToSubaccount) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgDepositToSubaccount) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgDepositToSubaccount) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.Quantums.Size()
		i -= size
		if _, err := m.Quantums.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintTransfer(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	if m.AssetId != 0 {
		i = encodeVarintTransfer(dAtA, i, uint64(m.AssetId))
		i--
		dAtA[i] = 0x18
	}
	{
		size, err := m.Recipient.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTransfer(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.Sender) > 0 {
		i -= len(m.Sender)
		copy(dAtA[i:], m.Sender)
		i = encodeVarintTransfer(dAtA, i, uint64(len(m.Sender)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgWithdrawFromSubaccount) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgWithdrawFromSubaccount) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgWithdrawFromSubaccount) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.Quantums.Size()
		i -= size
		if _, err := m.Quantums.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintTransfer(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	if m.AssetId != 0 {
		i = encodeVarintTransfer(dAtA, i, uint64(m.AssetId))
		i--
		dAtA[i] = 0x18
	}
	{
		size, err := m.Sender.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTransfer(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.Recipient) > 0 {
		i -= len(m.Recipient)
		copy(dAtA[i:], m.Recipient)
		i = encodeVarintTransfer(dAtA, i, uint64(len(m.Recipient)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgSendFromModuleToAccount) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSendFromModuleToAccount) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSendFromModuleToAccount) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Coin.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTransfer(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	if len(m.Recipient) > 0 {
		i -= len(m.Recipient)
		copy(dAtA[i:], m.Recipient)
		i = encodeVarintTransfer(dAtA, i, uint64(len(m.Recipient)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.SenderModuleName) > 0 {
		i -= len(m.SenderModuleName)
		copy(dAtA[i:], m.SenderModuleName)
		i = encodeVarintTransfer(dAtA, i, uint64(len(m.SenderModuleName)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Authority) > 0 {
		i -= len(m.Authority)
		copy(dAtA[i:], m.Authority)
		i = encodeVarintTransfer(dAtA, i, uint64(len(m.Authority)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintTransfer(dAtA []byte, offset int, v uint64) int {
	offset -= sovTransfer(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Transfer) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Sender.Size()
	n += 1 + l + sovTransfer(uint64(l))
	l = m.Recipient.Size()
	n += 1 + l + sovTransfer(uint64(l))
	if m.AssetId != 0 {
		n += 1 + sovTransfer(uint64(m.AssetId))
	}
	l = m.Amount.Size()
	n += 1 + l + sovTransfer(uint64(l))
	return n
}

func (m *MsgDepositToSubaccount) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Sender)
	if l > 0 {
		n += 1 + l + sovTransfer(uint64(l))
	}
	l = m.Recipient.Size()
	n += 1 + l + sovTransfer(uint64(l))
	if m.AssetId != 0 {
		n += 1 + sovTransfer(uint64(m.AssetId))
	}
	l = m.Quantums.Size()
	n += 1 + l + sovTransfer(uint64(l))
	return n
}

func (m *MsgWithdrawFromSubaccount) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Recipient)
	if l > 0 {
		n += 1 + l + sovTransfer(uint64(l))
	}
	l = m.Sender.Size()
	n += 1 + l + sovTransfer(uint64(l))
	if m.AssetId != 0 {
		n += 1 + sovTransfer(uint64(m.AssetId))
	}
	l = m.Quantums.Size()
	n += 1 + l + sovTransfer(uint64(l))
	return n
}

func (m *MsgSendFromModuleToAccount) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Authority)
	if l > 0 {
		n += 1 + l + sovTransfer(uint64(l))
	}
	l = len(m.SenderModuleName)
	if l > 0 {
		n += 1 + l + sovTransfer(uint64(l))
	}
	l = len(m.Recipient)
	if l > 0 {
		n += 1 + l + sovTransfer(uint64(l))
	}
	l = m.Coin.Size()
	n += 1 + l + sovTransfer(uint64(l))
	return n
}

func sovTransfer(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTransfer(x uint64) (n int) {
	return sovTransfer(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Transfer) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTransfer
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Transfer: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Transfer: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sender", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTransfer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTransfer
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTransfer
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Sender.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Recipient", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTransfer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTransfer
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTransfer
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Recipient.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AssetId", wireType)
			}
			m.AssetId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTransfer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AssetId |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTransfer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTransfer
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTransfer
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Amount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTransfer(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTransfer
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgDepositToSubaccount) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTransfer
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgDepositToSubaccount: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgDepositToSubaccount: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sender", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTransfer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTransfer
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTransfer
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Sender = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Recipient", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTransfer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTransfer
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTransfer
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Recipient.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AssetId", wireType)
			}
			m.AssetId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTransfer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AssetId |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Quantums", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTransfer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTransfer
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTransfer
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Quantums.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTransfer(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTransfer
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgWithdrawFromSubaccount) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTransfer
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgWithdrawFromSubaccount: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgWithdrawFromSubaccount: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Recipient", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTransfer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTransfer
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTransfer
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Recipient = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sender", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTransfer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTransfer
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTransfer
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Sender.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AssetId", wireType)
			}
			m.AssetId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTransfer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AssetId |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Quantums", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTransfer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTransfer
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTransfer
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Quantums.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTransfer(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTransfer
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSendFromModuleToAccount) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTransfer
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSendFromModuleToAccount: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSendFromModuleToAccount: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Authority", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTransfer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTransfer
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTransfer
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Authority = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SenderModuleName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTransfer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTransfer
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTransfer
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SenderModuleName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Recipient", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTransfer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTransfer
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTransfer
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Recipient = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Coin", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTransfer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTransfer
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTransfer
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Coin.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTransfer(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTransfer
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTransfer(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTransfer
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTransfer
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTransfer
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTransfer
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTransfer
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTransfer
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTransfer        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTransfer          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTransfer = fmt.Errorf("proto: unexpected end of group")
)
