// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: dydxprotocol/lendingaccount/lending_manager.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type LendingManager struct {
	// The name of the lending manager.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The base asset for the lending manager.
	AssetId uint32 `protobuf:"varint,2,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	// A map of enabled lending perpetuals.
	EnabledLendingPerpetuals map[uint32]*EnabledLendingPerpetual `protobuf:"bytes,3,rep,name=enabled_lending_perpetuals,json=enabledLendingPerpetuals,proto3" json:"enabled_lending_perpetuals,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// A map of enabled collateral assets.
	EnabledCollateralAssets map[uint32]*EnabledCollateralAssets `protobuf:"bytes,4,rep,name=enabled_collateral_assets,json=enabledCollateralAssets,proto3" json:"enabled_collateral_assets,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// Parameters for liquidation.
	LiquidationParams *LiquidationParams `protobuf:"bytes,5,opt,name=liquidation_params,json=liquidationParams,proto3" json:"liquidation_params,omitempty"`
	// The maximum leverage for perpetuals.
	MaxPerpetualLeverage uint64 `protobuf:"varint,6,opt,name=max_perpetual_leverage,json=maxPerpetualLeverage,proto3" json:"max_perpetual_leverage,omitempty"`
	// The interest fee.
	InterestFee uint64 `protobuf:"varint,7,opt,name=interest_fee,json=interestFee,proto3" json:"interest_fee,omitempty"`
	// Indicates if the lending manager is frozen.
	IsFrozen bool `protobuf:"varint,8,opt,name=is_frozen,json=isFrozen,proto3" json:"is_frozen,omitempty"`
	// A map from account number to address.
	AccountNumberToAddress map[uint32]string `protobuf:"bytes,9,rep,name=account_number_to_address,json=accountNumberToAddress,proto3" json:"account_number_to_address,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (m *LendingManager) Reset()         { *m = LendingManager{} }
func (m *LendingManager) String() string { return proto.CompactTextString(m) }
func (*LendingManager) ProtoMessage()    {}
func (*LendingManager) Descriptor() ([]byte, []int) {
	return fileDescriptor_f4cfdbfad57d36ca, []int{0}
}
func (m *LendingManager) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *LendingManager) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_LendingManager.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *LendingManager) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LendingManager.Merge(m, src)
}
func (m *LendingManager) XXX_Size() int {
	return m.Size()
}
func (m *LendingManager) XXX_DiscardUnknown() {
	xxx_messageInfo_LendingManager.DiscardUnknown(m)
}

var xxx_messageInfo_LendingManager proto.InternalMessageInfo

func (m *LendingManager) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *LendingManager) GetAssetId() uint32 {
	if m != nil {
		return m.AssetId
	}
	return 0
}

func (m *LendingManager) GetEnabledLendingPerpetuals() map[uint32]*EnabledLendingPerpetual {
	if m != nil {
		return m.EnabledLendingPerpetuals
	}
	return nil
}

func (m *LendingManager) GetEnabledCollateralAssets() map[uint32]*EnabledCollateralAssets {
	if m != nil {
		return m.EnabledCollateralAssets
	}
	return nil
}

func (m *LendingManager) GetLiquidationParams() *LiquidationParams {
	if m != nil {
		return m.LiquidationParams
	}
	return nil
}

func (m *LendingManager) GetMaxPerpetualLeverage() uint64 {
	if m != nil {
		return m.MaxPerpetualLeverage
	}
	return 0
}

func (m *LendingManager) GetInterestFee() uint64 {
	if m != nil {
		return m.InterestFee
	}
	return 0
}

func (m *LendingManager) GetIsFrozen() bool {
	if m != nil {
		return m.IsFrozen
	}
	return false
}

func (m *LendingManager) GetAccountNumberToAddress() map[uint32]string {
	if m != nil {
		return m.AccountNumberToAddress
	}
	return nil
}

type EnabledLendingPerpetual struct {
	// Indicates if the account is enabled to go long or short.
	LongEnabled  bool `protobuf:"varint,1,opt,name=long_enabled,json=longEnabled,proto3" json:"long_enabled,omitempty"`
	ShortEnabled bool `protobuf:"varint,2,opt,name=short_enabled,json=shortEnabled,proto3" json:"short_enabled,omitempty"`
}

func (m *EnabledLendingPerpetual) Reset()         { *m = EnabledLendingPerpetual{} }
func (m *EnabledLendingPerpetual) String() string { return proto.CompactTextString(m) }
func (*EnabledLendingPerpetual) ProtoMessage()    {}
func (*EnabledLendingPerpetual) Descriptor() ([]byte, []int) {
	return fileDescriptor_f4cfdbfad57d36ca, []int{1}
}
func (m *EnabledLendingPerpetual) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EnabledLendingPerpetual) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EnabledLendingPerpetual.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EnabledLendingPerpetual) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnabledLendingPerpetual.Merge(m, src)
}
func (m *EnabledLendingPerpetual) XXX_Size() int {
	return m.Size()
}
func (m *EnabledLendingPerpetual) XXX_DiscardUnknown() {
	xxx_messageInfo_EnabledLendingPerpetual.DiscardUnknown(m)
}

var xxx_messageInfo_EnabledLendingPerpetual proto.InternalMessageInfo

func (m *EnabledLendingPerpetual) GetLongEnabled() bool {
	if m != nil {
		return m.LongEnabled
	}
	return false
}

func (m *EnabledLendingPerpetual) GetShortEnabled() bool {
	if m != nil {
		return m.ShortEnabled
	}
	return false
}

type EnabledCollateralAssets struct {
	// The collateral ratio.
	CollateralRatio uint64 `protobuf:"varint,1,opt,name=collateral_ratio,json=collateralRatio,proto3" json:"collateral_ratio,omitempty"`
}

func (m *EnabledCollateralAssets) Reset()         { *m = EnabledCollateralAssets{} }
func (m *EnabledCollateralAssets) String() string { return proto.CompactTextString(m) }
func (*EnabledCollateralAssets) ProtoMessage()    {}
func (*EnabledCollateralAssets) Descriptor() ([]byte, []int) {
	return fileDescriptor_f4cfdbfad57d36ca, []int{2}
}
func (m *EnabledCollateralAssets) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EnabledCollateralAssets) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EnabledCollateralAssets.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EnabledCollateralAssets) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnabledCollateralAssets.Merge(m, src)
}
func (m *EnabledCollateralAssets) XXX_Size() int {
	return m.Size()
}
func (m *EnabledCollateralAssets) XXX_DiscardUnknown() {
	xxx_messageInfo_EnabledCollateralAssets.DiscardUnknown(m)
}

var xxx_messageInfo_EnabledCollateralAssets proto.InternalMessageInfo

func (m *EnabledCollateralAssets) GetCollateralRatio() uint64 {
	if m != nil {
		return m.CollateralRatio
	}
	return 0
}

type LiquidationParams struct {
	// The liquidation threshold.
	LiquidationThreshold uint64 `protobuf:"varint,1,opt,name=liquidation_threshold,json=liquidationThreshold,proto3" json:"liquidation_threshold,omitempty"`
	// The liquidation discount.
	LiquidationDiscount uint64 `protobuf:"varint,2,opt,name=liquidation_discount,json=liquidationDiscount,proto3" json:"liquidation_discount,omitempty"`
	// The liquidation fee.
	LiquidationFee uint64 `protobuf:"varint,3,opt,name=liquidation_fee,json=liquidationFee,proto3" json:"liquidation_fee,omitempty"`
}

func (m *LiquidationParams) Reset()         { *m = LiquidationParams{} }
func (m *LiquidationParams) String() string { return proto.CompactTextString(m) }
func (*LiquidationParams) ProtoMessage()    {}
func (*LiquidationParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_f4cfdbfad57d36ca, []int{3}
}
func (m *LiquidationParams) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *LiquidationParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_LiquidationParams.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *LiquidationParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LiquidationParams.Merge(m, src)
}
func (m *LiquidationParams) XXX_Size() int {
	return m.Size()
}
func (m *LiquidationParams) XXX_DiscardUnknown() {
	xxx_messageInfo_LiquidationParams.DiscardUnknown(m)
}

var xxx_messageInfo_LiquidationParams proto.InternalMessageInfo

func (m *LiquidationParams) GetLiquidationThreshold() uint64 {
	if m != nil {
		return m.LiquidationThreshold
	}
	return 0
}

func (m *LiquidationParams) GetLiquidationDiscount() uint64 {
	if m != nil {
		return m.LiquidationDiscount
	}
	return 0
}

func (m *LiquidationParams) GetLiquidationFee() uint64 {
	if m != nil {
		return m.LiquidationFee
	}
	return 0
}

func init() {
	proto.RegisterType((*LendingManager)(nil), "dydxprotocol.lendingaccount.LendingManager")
	proto.RegisterMapType((map[uint32]string)(nil), "dydxprotocol.lendingaccount.LendingManager.AccountNumberToAddressEntry")
	proto.RegisterMapType((map[uint32]*EnabledCollateralAssets)(nil), "dydxprotocol.lendingaccount.LendingManager.EnabledCollateralAssetsEntry")
	proto.RegisterMapType((map[uint32]*EnabledLendingPerpetual)(nil), "dydxprotocol.lendingaccount.LendingManager.EnabledLendingPerpetualsEntry")
	proto.RegisterType((*EnabledLendingPerpetual)(nil), "dydxprotocol.lendingaccount.EnabledLendingPerpetual")
	proto.RegisterType((*EnabledCollateralAssets)(nil), "dydxprotocol.lendingaccount.EnabledCollateralAssets")
	proto.RegisterType((*LiquidationParams)(nil), "dydxprotocol.lendingaccount.LiquidationParams")
}

func init() {
	proto.RegisterFile("dydxprotocol/lendingaccount/lending_manager.proto", fileDescriptor_f4cfdbfad57d36ca)
}

var fileDescriptor_f4cfdbfad57d36ca = []byte{
	// 699 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x55, 0xbd, 0x6e, 0x13, 0x4d,
	0x14, 0xcd, 0xc4, 0x4e, 0x62, 0x8f, 0xf3, 0x3b, 0x9f, 0xbf, 0x64, 0xed, 0x80, 0x65, 0x4c, 0x81,
	0x29, 0x62, 0x2b, 0x3f, 0x05, 0xa2, 0x4b, 0x48, 0x0c, 0x41, 0x21, 0x8a, 0x36, 0xa9, 0x90, 0xd0,
	0x68, 0xbc, 0x7b, 0xb3, 0x5e, 0xb1, 0x3b, 0x63, 0x66, 0xc6, 0x91, 0x4d, 0x05, 0x12, 0x12, 0x2d,
	0x15, 0x15, 0x25, 0x8f, 0xc0, 0x43, 0x50, 0x46, 0x54, 0x94, 0x28, 0x79, 0x11, 0xe4, 0xd9, 0xb5,
	0xb3, 0xf9, 0xb3, 0x04, 0xa2, 0xdb, 0x39, 0xe7, 0x9e, 0x33, 0x67, 0xaf, 0xee, 0xd5, 0xe0, 0x55,
	0xb7, 0xe7, 0x76, 0xdb, 0x52, 0x68, 0xe1, 0x88, 0xa0, 0x1e, 0x00, 0x77, 0x7d, 0xee, 0x31, 0xc7,
	0x11, 0x1d, 0xae, 0x07, 0x47, 0x1a, 0x32, 0xce, 0x3c, 0x90, 0x35, 0x53, 0x47, 0x96, 0x93, 0x92,
	0xda, 0x65, 0x49, 0x31, 0xef, 0x09, 0x4f, 0x18, 0xb2, 0xde, 0xff, 0x8a, 0x24, 0xc5, 0x82, 0x23,
	0x54, 0x28, 0x14, 0x8d, 0x88, 0xe8, 0x10, 0x51, 0x95, 0xcf, 0x19, 0x3c, 0xbb, 0x17, 0x79, 0xbc,
	0x88, 0xae, 0x21, 0x04, 0xa7, 0x39, 0x0b, 0xc1, 0x42, 0x65, 0x54, 0xcd, 0xda, 0xe6, 0x9b, 0x14,
	0x70, 0x86, 0x29, 0x05, 0x9a, 0xfa, 0xae, 0x35, 0x5e, 0x46, 0xd5, 0x19, 0x7b, 0xca, 0x9c, 0x77,
	0x5d, 0xf2, 0x11, 0xe1, 0x22, 0x70, 0xd6, 0x0c, 0xc0, 0xa5, 0x83, 0xc4, 0x6d, 0x90, 0x6d, 0xd0,
	0x1d, 0x16, 0x28, 0x2b, 0x55, 0x4e, 0x55, 0x73, 0x6b, 0xbb, 0xb5, 0x11, 0xa9, 0x6b, 0x97, 0x03,
	0xd4, 0x76, 0x22, 0xb7, 0x18, 0x3d, 0x18, 0x7a, 0xed, 0x70, 0x2d, 0x7b, 0xb6, 0x05, 0xb7, 0xd0,
	0xe4, 0x03, 0xc2, 0x85, 0x41, 0x12, 0x47, 0x04, 0x01, 0xd3, 0x20, 0x59, 0x40, 0x4d, 0x50, 0x65,
	0xa5, 0x4d, 0x90, 0x67, 0x7f, 0x11, 0xe4, 0xc9, 0xd0, 0x6b, 0xd3, 0x58, 0x45, 0x39, 0x96, 0xe0,
	0x66, 0x96, 0xbc, 0xc2, 0x24, 0xf0, 0xdf, 0x74, 0x7c, 0x97, 0x69, 0x5f, 0x70, 0xda, 0x66, 0x92,
	0x85, 0xca, 0x9a, 0x28, 0xa3, 0x6a, 0x6e, 0xad, 0x36, 0xfa, 0xfa, 0x0b, 0xd9, 0x81, 0x51, 0xd9,
	0x0b, 0xc1, 0x55, 0x88, 0x6c, 0xe0, 0xc5, 0x90, 0x75, 0x2f, 0x5a, 0x4c, 0x03, 0x38, 0x01, 0xc9,
	0x3c, 0xb0, 0x26, 0xcb, 0xa8, 0x9a, 0xb6, 0xf3, 0x21, 0xeb, 0x0e, 0x9b, 0xb2, 0x17, 0x73, 0xe4,
	0x1e, 0x9e, 0xf6, 0xb9, 0x06, 0x09, 0x4a, 0xd3, 0x63, 0x00, 0x6b, 0xca, 0xd4, 0xe6, 0x06, 0x58,
	0x03, 0x80, 0x2c, 0xe3, 0xac, 0xaf, 0xe8, 0xb1, 0x14, 0x6f, 0x81, 0x5b, 0x99, 0x32, 0xaa, 0x66,
	0xec, 0x8c, 0xaf, 0x1a, 0xe6, 0x4c, 0xbe, 0x20, 0x5c, 0x88, 0x63, 0x52, 0xde, 0x09, 0x9b, 0x20,
	0xa9, 0x16, 0x94, 0xb9, 0xae, 0x04, 0xa5, 0xac, 0xac, 0xe9, 0xed, 0xd3, 0x3f, 0xe9, 0xed, 0x66,
	0x04, 0xef, 0x1b, 0xaf, 0x23, 0xb1, 0x19, 0x39, 0x99, 0xd6, 0x6e, 0x59, 0x3f, 0xbe, 0xad, 0xe4,
	0xe3, 0x31, 0x8d, 0x89, 0x43, 0x2d, 0x7d, 0xee, 0xd9, 0x8b, 0xec, 0x46, 0x59, 0xf1, 0x3d, 0xc2,
	0x77, 0x47, 0x8e, 0x0d, 0x99, 0xc7, 0xa9, 0xd7, 0xd0, 0x33, 0x43, 0x3d, 0x63, 0xf7, 0x3f, 0xc9,
	0x73, 0x3c, 0x71, 0xc2, 0x82, 0x0e, 0x98, 0x81, 0xce, 0xad, 0x6d, 0x8c, 0x4c, 0x7f, 0x8b, 0xb9,
	0x1d, 0x59, 0x3c, 0x1e, 0x7f, 0x84, 0x8a, 0xef, 0x10, 0xbe, 0x33, 0x6a, 0x62, 0xfe, 0x51, 0x84,
	0xab, 0xde, 0xc9, 0x08, 0xbb, 0x78, 0x79, 0x44, 0x5f, 0x6f, 0x08, 0x90, 0x4f, 0x06, 0xc8, 0x26,
	0xac, 0x2a, 0x0c, 0x2f, 0xdd, 0xf2, 0xcf, 0xfd, 0x59, 0x0a, 0x04, 0xf7, 0x68, 0xbc, 0x00, 0xc6,
	0x2f, 0x63, 0xe7, 0xfa, 0x58, 0x2c, 0x21, 0xf7, 0xf1, 0x8c, 0x6a, 0x09, 0xa9, 0x87, 0x35, 0xe3,
	0xa6, 0x66, 0xda, 0x80, 0x71, 0x51, 0x65, 0x7b, 0x78, 0xc5, 0xb5, 0x1d, 0x7a, 0x88, 0xe7, 0x13,
	0x1b, 0x2c, 0xfb, 0xf3, 0x6f, 0xae, 0x49, 0xdb, 0x73, 0x17, 0xb8, 0xdd, 0x87, 0x2b, 0x5f, 0x11,
	0x5e, 0xb8, 0xb6, 0x38, 0x64, 0x1d, 0xff, 0x9f, 0x5c, 0x42, 0xdd, 0x92, 0xa0, 0x5a, 0x22, 0x70,
	0x63, 0x97, 0x7c, 0x82, 0x3c, 0x1a, 0x70, 0x64, 0x15, 0x27, 0x71, 0xea, 0xfa, 0xca, 0xf4, 0xd2,
	0x84, 0x4f, 0xdb, 0xff, 0x25, 0xb8, 0xed, 0x98, 0x22, 0x0f, 0xf0, 0x5c, 0x52, 0xd2, 0x5f, 0xad,
	0x94, 0xa9, 0x9e, 0x4d, 0xc0, 0x0d, 0x80, 0xad, 0xd6, 0xf7, 0xb3, 0x12, 0x3a, 0x3d, 0x2b, 0xa1,
	0x5f, 0x67, 0x25, 0xf4, 0xe9, 0xbc, 0x34, 0x76, 0x7a, 0x5e, 0x1a, 0xfb, 0x79, 0x5e, 0x1a, 0x7b,
	0xb9, 0xef, 0xf9, 0xba, 0xd5, 0x69, 0xd6, 0x1c, 0x11, 0xd6, 0x0f, 0xb5, 0x04, 0x16, 0x36, 0x7c,
	0xce, 0xb8, 0x03, 0x2b, 0x07, 0x83, 0x87, 0x41, 0x19, 0x78, 0xc5, 0x69, 0x31, 0x9f, 0xd7, 0x87,
	0xcf, 0x45, 0xf7, 0xea, 0x83, 0xa1, 0x7b, 0x6d, 0x50, 0xcd, 0x49, 0x53, 0xb0, 0xfe, 0x3b, 0x00,
	0x00, 0xff, 0xff, 0xbd, 0xcc, 0x43, 0xd3, 0x5c, 0x06, 0x00, 0x00,
}

func (m *LendingManager) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *LendingManager) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *LendingManager) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.AccountNumberToAddress) > 0 {
		for k := range m.AccountNumberToAddress {
			v := m.AccountNumberToAddress[k]
			baseI := i
			i -= len(v)
			copy(dAtA[i:], v)
			i = encodeVarintLendingManager(dAtA, i, uint64(len(v)))
			i--
			dAtA[i] = 0x12
			i = encodeVarintLendingManager(dAtA, i, uint64(k))
			i--
			dAtA[i] = 0x8
			i = encodeVarintLendingManager(dAtA, i, uint64(baseI-i))
			i--
			dAtA[i] = 0x4a
		}
	}
	if m.IsFrozen {
		i--
		if m.IsFrozen {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x40
	}
	if m.InterestFee != 0 {
		i = encodeVarintLendingManager(dAtA, i, uint64(m.InterestFee))
		i--
		dAtA[i] = 0x38
	}
	if m.MaxPerpetualLeverage != 0 {
		i = encodeVarintLendingManager(dAtA, i, uint64(m.MaxPerpetualLeverage))
		i--
		dAtA[i] = 0x30
	}
	if m.LiquidationParams != nil {
		{
			size, err := m.LiquidationParams.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintLendingManager(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x2a
	}
	if len(m.EnabledCollateralAssets) > 0 {
		for k := range m.EnabledCollateralAssets {
			v := m.EnabledCollateralAssets[k]
			baseI := i
			if v != nil {
				{
					size, err := v.MarshalToSizedBuffer(dAtA[:i])
					if err != nil {
						return 0, err
					}
					i -= size
					i = encodeVarintLendingManager(dAtA, i, uint64(size))
				}
				i--
				dAtA[i] = 0x12
			}
			i = encodeVarintLendingManager(dAtA, i, uint64(k))
			i--
			dAtA[i] = 0x8
			i = encodeVarintLendingManager(dAtA, i, uint64(baseI-i))
			i--
			dAtA[i] = 0x22
		}
	}
	if len(m.EnabledLendingPerpetuals) > 0 {
		for k := range m.EnabledLendingPerpetuals {
			v := m.EnabledLendingPerpetuals[k]
			baseI := i
			if v != nil {
				{
					size, err := v.MarshalToSizedBuffer(dAtA[:i])
					if err != nil {
						return 0, err
					}
					i -= size
					i = encodeVarintLendingManager(dAtA, i, uint64(size))
				}
				i--
				dAtA[i] = 0x12
			}
			i = encodeVarintLendingManager(dAtA, i, uint64(k))
			i--
			dAtA[i] = 0x8
			i = encodeVarintLendingManager(dAtA, i, uint64(baseI-i))
			i--
			dAtA[i] = 0x1a
		}
	}
	if m.AssetId != 0 {
		i = encodeVarintLendingManager(dAtA, i, uint64(m.AssetId))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintLendingManager(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *EnabledLendingPerpetual) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EnabledLendingPerpetual) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EnabledLendingPerpetual) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ShortEnabled {
		i--
		if m.ShortEnabled {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x10
	}
	if m.LongEnabled {
		i--
		if m.LongEnabled {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *EnabledCollateralAssets) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EnabledCollateralAssets) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EnabledCollateralAssets) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.CollateralRatio != 0 {
		i = encodeVarintLendingManager(dAtA, i, uint64(m.CollateralRatio))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *LiquidationParams) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *LiquidationParams) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *LiquidationParams) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.LiquidationFee != 0 {
		i = encodeVarintLendingManager(dAtA, i, uint64(m.LiquidationFee))
		i--
		dAtA[i] = 0x18
	}
	if m.LiquidationDiscount != 0 {
		i = encodeVarintLendingManager(dAtA, i, uint64(m.LiquidationDiscount))
		i--
		dAtA[i] = 0x10
	}
	if m.LiquidationThreshold != 0 {
		i = encodeVarintLendingManager(dAtA, i, uint64(m.LiquidationThreshold))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintLendingManager(dAtA []byte, offset int, v uint64) int {
	offset -= sovLendingManager(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *LendingManager) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovLendingManager(uint64(l))
	}
	if m.AssetId != 0 {
		n += 1 + sovLendingManager(uint64(m.AssetId))
	}
	if len(m.EnabledLendingPerpetuals) > 0 {
		for k, v := range m.EnabledLendingPerpetuals {
			_ = k
			_ = v
			l = 0
			if v != nil {
				l = v.Size()
				l += 1 + sovLendingManager(uint64(l))
			}
			mapEntrySize := 1 + sovLendingManager(uint64(k)) + l
			n += mapEntrySize + 1 + sovLendingManager(uint64(mapEntrySize))
		}
	}
	if len(m.EnabledCollateralAssets) > 0 {
		for k, v := range m.EnabledCollateralAssets {
			_ = k
			_ = v
			l = 0
			if v != nil {
				l = v.Size()
				l += 1 + sovLendingManager(uint64(l))
			}
			mapEntrySize := 1 + sovLendingManager(uint64(k)) + l
			n += mapEntrySize + 1 + sovLendingManager(uint64(mapEntrySize))
		}
	}
	if m.LiquidationParams != nil {
		l = m.LiquidationParams.Size()
		n += 1 + l + sovLendingManager(uint64(l))
	}
	if m.MaxPerpetualLeverage != 0 {
		n += 1 + sovLendingManager(uint64(m.MaxPerpetualLeverage))
	}
	if m.InterestFee != 0 {
		n += 1 + sovLendingManager(uint64(m.InterestFee))
	}
	if m.IsFrozen {
		n += 2
	}
	if len(m.AccountNumberToAddress) > 0 {
		for k, v := range m.AccountNumberToAddress {
			_ = k
			_ = v
			mapEntrySize := 1 + sovLendingManager(uint64(k)) + 1 + len(v) + sovLendingManager(uint64(len(v)))
			n += mapEntrySize + 1 + sovLendingManager(uint64(mapEntrySize))
		}
	}
	return n
}

func (m *EnabledLendingPerpetual) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.LongEnabled {
		n += 2
	}
	if m.ShortEnabled {
		n += 2
	}
	return n
}

func (m *EnabledCollateralAssets) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.CollateralRatio != 0 {
		n += 1 + sovLendingManager(uint64(m.CollateralRatio))
	}
	return n
}

func (m *LiquidationParams) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.LiquidationThreshold != 0 {
		n += 1 + sovLendingManager(uint64(m.LiquidationThreshold))
	}
	if m.LiquidationDiscount != 0 {
		n += 1 + sovLendingManager(uint64(m.LiquidationDiscount))
	}
	if m.LiquidationFee != 0 {
		n += 1 + sovLendingManager(uint64(m.LiquidationFee))
	}
	return n
}

func sovLendingManager(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozLendingManager(x uint64) (n int) {
	return sovLendingManager(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *LendingManager) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowLendingManager
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: LendingManager: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: LendingManager: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLendingManager
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLendingManager
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLendingManager
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AssetId", wireType)
			}
			m.AssetId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLendingManager
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AssetId |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EnabledLendingPerpetuals", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLendingManager
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthLendingManager
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthLendingManager
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.EnabledLendingPerpetuals == nil {
				m.EnabledLendingPerpetuals = make(map[uint32]*EnabledLendingPerpetual)
			}
			var mapkey uint32
			var mapvalue *EnabledLendingPerpetual
			for iNdEx < postIndex {
				entryPreIndex := iNdEx
				var wire uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowLendingManager
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					wire |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				fieldNum := int32(wire >> 3)
				if fieldNum == 1 {
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowLendingManager
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						mapkey |= uint32(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
				} else if fieldNum == 2 {
					var mapmsglen int
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowLendingManager
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						mapmsglen |= int(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					if mapmsglen < 0 {
						return ErrInvalidLengthLendingManager
					}
					postmsgIndex := iNdEx + mapmsglen
					if postmsgIndex < 0 {
						return ErrInvalidLengthLendingManager
					}
					if postmsgIndex > l {
						return io.ErrUnexpectedEOF
					}
					mapvalue = &EnabledLendingPerpetual{}
					if err := mapvalue.Unmarshal(dAtA[iNdEx:postmsgIndex]); err != nil {
						return err
					}
					iNdEx = postmsgIndex
				} else {
					iNdEx = entryPreIndex
					skippy, err := skipLendingManager(dAtA[iNdEx:])
					if err != nil {
						return err
					}
					if (skippy < 0) || (iNdEx+skippy) < 0 {
						return ErrInvalidLengthLendingManager
					}
					if (iNdEx + skippy) > postIndex {
						return io.ErrUnexpectedEOF
					}
					iNdEx += skippy
				}
			}
			m.EnabledLendingPerpetuals[mapkey] = mapvalue
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EnabledCollateralAssets", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLendingManager
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthLendingManager
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthLendingManager
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.EnabledCollateralAssets == nil {
				m.EnabledCollateralAssets = make(map[uint32]*EnabledCollateralAssets)
			}
			var mapkey uint32
			var mapvalue *EnabledCollateralAssets
			for iNdEx < postIndex {
				entryPreIndex := iNdEx
				var wire uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowLendingManager
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					wire |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				fieldNum := int32(wire >> 3)
				if fieldNum == 1 {
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowLendingManager
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						mapkey |= uint32(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
				} else if fieldNum == 2 {
					var mapmsglen int
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowLendingManager
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						mapmsglen |= int(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					if mapmsglen < 0 {
						return ErrInvalidLengthLendingManager
					}
					postmsgIndex := iNdEx + mapmsglen
					if postmsgIndex < 0 {
						return ErrInvalidLengthLendingManager
					}
					if postmsgIndex > l {
						return io.ErrUnexpectedEOF
					}
					mapvalue = &EnabledCollateralAssets{}
					if err := mapvalue.Unmarshal(dAtA[iNdEx:postmsgIndex]); err != nil {
						return err
					}
					iNdEx = postmsgIndex
				} else {
					iNdEx = entryPreIndex
					skippy, err := skipLendingManager(dAtA[iNdEx:])
					if err != nil {
						return err
					}
					if (skippy < 0) || (iNdEx+skippy) < 0 {
						return ErrInvalidLengthLendingManager
					}
					if (iNdEx + skippy) > postIndex {
						return io.ErrUnexpectedEOF
					}
					iNdEx += skippy
				}
			}
			m.EnabledCollateralAssets[mapkey] = mapvalue
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LiquidationParams", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLendingManager
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthLendingManager
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthLendingManager
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.LiquidationParams == nil {
				m.LiquidationParams = &LiquidationParams{}
			}
			if err := m.LiquidationParams.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxPerpetualLeverage", wireType)
			}
			m.MaxPerpetualLeverage = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLendingManager
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxPerpetualLeverage |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field InterestFee", wireType)
			}
			m.InterestFee = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLendingManager
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.InterestFee |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IsFrozen", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLendingManager
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.IsFrozen = bool(v != 0)
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AccountNumberToAddress", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLendingManager
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthLendingManager
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthLendingManager
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.AccountNumberToAddress == nil {
				m.AccountNumberToAddress = make(map[uint32]string)
			}
			var mapkey uint32
			var mapvalue string
			for iNdEx < postIndex {
				entryPreIndex := iNdEx
				var wire uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowLendingManager
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					wire |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				fieldNum := int32(wire >> 3)
				if fieldNum == 1 {
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowLendingManager
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						mapkey |= uint32(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
				} else if fieldNum == 2 {
					var stringLenmapvalue uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowLendingManager
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						stringLenmapvalue |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					intStringLenmapvalue := int(stringLenmapvalue)
					if intStringLenmapvalue < 0 {
						return ErrInvalidLengthLendingManager
					}
					postStringIndexmapvalue := iNdEx + intStringLenmapvalue
					if postStringIndexmapvalue < 0 {
						return ErrInvalidLengthLendingManager
					}
					if postStringIndexmapvalue > l {
						return io.ErrUnexpectedEOF
					}
					mapvalue = string(dAtA[iNdEx:postStringIndexmapvalue])
					iNdEx = postStringIndexmapvalue
				} else {
					iNdEx = entryPreIndex
					skippy, err := skipLendingManager(dAtA[iNdEx:])
					if err != nil {
						return err
					}
					if (skippy < 0) || (iNdEx+skippy) < 0 {
						return ErrInvalidLengthLendingManager
					}
					if (iNdEx + skippy) > postIndex {
						return io.ErrUnexpectedEOF
					}
					iNdEx += skippy
				}
			}
			m.AccountNumberToAddress[mapkey] = mapvalue
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipLendingManager(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthLendingManager
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EnabledLendingPerpetual) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowLendingManager
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EnabledLendingPerpetual: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EnabledLendingPerpetual: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LongEnabled", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLendingManager
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.LongEnabled = bool(v != 0)
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ShortEnabled", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLendingManager
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.ShortEnabled = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipLendingManager(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthLendingManager
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EnabledCollateralAssets) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowLendingManager
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EnabledCollateralAssets: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EnabledCollateralAssets: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CollateralRatio", wireType)
			}
			m.CollateralRatio = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLendingManager
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CollateralRatio |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipLendingManager(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthLendingManager
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *LiquidationParams) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowLendingManager
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: LiquidationParams: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: LiquidationParams: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LiquidationThreshold", wireType)
			}
			m.LiquidationThreshold = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLendingManager
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LiquidationThreshold |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LiquidationDiscount", wireType)
			}
			m.LiquidationDiscount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLendingManager
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LiquidationDiscount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LiquidationFee", wireType)
			}
			m.LiquidationFee = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLendingManager
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LiquidationFee |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipLendingManager(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthLendingManager
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipLendingManager(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowLendingManager
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowLendingManager
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowLendingManager
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthLendingManager
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupLendingManager
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthLendingManager
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthLendingManager        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowLendingManager          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupLendingManager = fmt.Errorf("proto: unexpected end of group")
)
