// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: klyraprotocol/clob/liquidations_config.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// LiquidationsConfig stores all configurable fields related to liquidations.
type LiquidationsConfig struct {
	// The maximum liquidation fee (in parts-per-million). This fee goes
	// 100% to the insurance fund.
	InsuranceFundFeePpm uint32 `protobuf:"varint,1,opt,name=insurance_fund_fee_ppm,json=insuranceFundFeePpm,proto3" json:"insurance_fund_fee_ppm,omitempty"`
	// The fraction of the remaining collateral taken as a validator fee.
	ValidatorFeePpm uint32 `protobuf:"varint,2,opt,name=validator_fee_ppm,json=validatorFeePpm,proto3" json:"validator_fee_ppm,omitempty"`
	// The fraction of the remaining collateral taken as a liquidity fee.
	LiquidityFeePpm uint32 `protobuf:"varint,3,opt,name=liquidity_fee_ppm,json=liquidityFeePpm,proto3" json:"liquidity_fee_ppm,omitempty"`
	// Config about how the fillable-price spread from the oracle price
	// increases based on the adjusted bankruptcy rating of the subaccount.
	FillablePriceConfig FillablePriceConfig `protobuf:"bytes,4,opt,name=fillable_price_config,json=fillablePriceConfig,proto3" json:"fillable_price_config"`
}

func (m *LiquidationsConfig) Reset()         { *m = LiquidationsConfig{} }
func (m *LiquidationsConfig) String() string { return proto.CompactTextString(m) }
func (*LiquidationsConfig) ProtoMessage()    {}
func (*LiquidationsConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_93acb41339cdff26, []int{0}
}
func (m *LiquidationsConfig) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *LiquidationsConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_LiquidationsConfig.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *LiquidationsConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LiquidationsConfig.Merge(m, src)
}
func (m *LiquidationsConfig) XXX_Size() int {
	return m.Size()
}
func (m *LiquidationsConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_LiquidationsConfig.DiscardUnknown(m)
}

var xxx_messageInfo_LiquidationsConfig proto.InternalMessageInfo

func (m *LiquidationsConfig) GetInsuranceFundFeePpm() uint32 {
	if m != nil {
		return m.InsuranceFundFeePpm
	}
	return 0
}

func (m *LiquidationsConfig) GetValidatorFeePpm() uint32 {
	if m != nil {
		return m.ValidatorFeePpm
	}
	return 0
}

func (m *LiquidationsConfig) GetLiquidityFeePpm() uint32 {
	if m != nil {
		return m.LiquidityFeePpm
	}
	return 0
}

func (m *LiquidationsConfig) GetFillablePriceConfig() FillablePriceConfig {
	if m != nil {
		return m.FillablePriceConfig
	}
	return FillablePriceConfig{}
}

// FillablePriceConfig stores all configurable fields related to calculating
// the fillable price for liquidating a position.
type FillablePriceConfig struct {
	// The rate at which the Adjusted Bankruptcy Rating increases.
	BankruptcyAdjustmentPpm uint32 `protobuf:"varint,1,opt,name=bankruptcy_adjustment_ppm,json=bankruptcyAdjustmentPpm,proto3" json:"bankruptcy_adjustment_ppm,omitempty"`
	// The maximum value that the liquidation spread can take, as
	// a ratio against the position's maintenance margin.
	SpreadToMaintenanceMarginRatioPpm uint32 `protobuf:"varint,2,opt,name=spread_to_maintenance_margin_ratio_ppm,json=spreadToMaintenanceMarginRatioPpm,proto3" json:"spread_to_maintenance_margin_ratio_ppm,omitempty"`
}

func (m *FillablePriceConfig) Reset()         { *m = FillablePriceConfig{} }
func (m *FillablePriceConfig) String() string { return proto.CompactTextString(m) }
func (*FillablePriceConfig) ProtoMessage()    {}
func (*FillablePriceConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_93acb41339cdff26, []int{1}
}
func (m *FillablePriceConfig) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *FillablePriceConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_FillablePriceConfig.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *FillablePriceConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FillablePriceConfig.Merge(m, src)
}
func (m *FillablePriceConfig) XXX_Size() int {
	return m.Size()
}
func (m *FillablePriceConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_FillablePriceConfig.DiscardUnknown(m)
}

var xxx_messageInfo_FillablePriceConfig proto.InternalMessageInfo

func (m *FillablePriceConfig) GetBankruptcyAdjustmentPpm() uint32 {
	if m != nil {
		return m.BankruptcyAdjustmentPpm
	}
	return 0
}

func (m *FillablePriceConfig) GetSpreadToMaintenanceMarginRatioPpm() uint32 {
	if m != nil {
		return m.SpreadToMaintenanceMarginRatioPpm
	}
	return 0
}

func init() {
	proto.RegisterType((*LiquidationsConfig)(nil), "klyraprotocol.clob.LiquidationsConfig")
	proto.RegisterType((*FillablePriceConfig)(nil), "klyraprotocol.clob.FillablePriceConfig")
}

func init() {
	proto.RegisterFile("klyraprotocol/clob/liquidations_config.proto", fileDescriptor_93acb41339cdff26)
}

var fileDescriptor_93acb41339cdff26 = []byte{
	// 391 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0xd2, 0xbd, 0x8e, 0xd3, 0x40,
	0x10, 0x07, 0x70, 0x3b, 0x44, 0x14, 0x8b, 0x10, 0xc2, 0xe1, 0x23, 0x50, 0x98, 0x90, 0x02, 0x22,
	0x44, 0x6c, 0x89, 0x74, 0x74, 0x04, 0xe4, 0x8a, 0x48, 0x26, 0x50, 0x51, 0xb0, 0x5a, 0xaf, 0xd7,
	0xce, 0x92, 0xfd, 0xba, 0xf5, 0xfa, 0x74, 0xee, 0xef, 0x01, 0xee, 0x21, 0xee, 0x61, 0x52, 0xa6,
	0xbc, 0xea, 0x74, 0x4a, 0x5e, 0xe4, 0xe4, 0x75, 0xce, 0xc9, 0x29, 0xd7, 0x59, 0xf3, 0xff, 0x79,
	0xb4, 0x33, 0x1a, 0xf0, 0x79, 0xc9, 0x2a, 0x8d, 0x94, 0x96, 0x46, 0x62, 0xc9, 0x42, 0xcc, 0x64,
	0x12, 0x32, 0x7a, 0x52, 0xd2, 0x14, 0x19, 0x2a, 0x45, 0x01, 0xb1, 0x14, 0x19, 0xcd, 0x03, 0x2b,
	0x3c, 0xef, 0x9e, 0x0e, 0x6a, 0xfd, 0xf6, 0x45, 0x2e, 0x73, 0x69, 0x4b, 0x61, 0xfd, 0xd5, 0xc8,
	0xe1, 0x79, 0x07, 0x78, 0x3f, 0x0f, 0xfa, 0x7c, 0xb7, 0x6d, 0xbc, 0x09, 0x78, 0x45, 0x45, 0x51,
	0x6a, 0x24, 0x30, 0x81, 0x59, 0x29, 0x52, 0x98, 0x11, 0x02, 0x95, 0xe2, 0x7d, 0x77, 0xe0, 0x8e,
	0x9e, 0xce, 0x7b, 0x6d, 0x1a, 0x95, 0x22, 0x8d, 0x08, 0x89, 0x15, 0xf7, 0x3e, 0x81, 0xe7, 0xa7,
	0x88, 0xd5, 0x9d, 0xa4, 0x6e, 0x7d, 0xc7, 0xfa, 0x67, 0x6d, 0xb0, 0xb7, 0xcd, 0xf3, 0xa9, 0xa9,
	0x5a, 0xfb, 0xa8, 0xb1, 0x6d, 0xb0, 0xb3, 0x08, 0xbc, 0xcc, 0x28, 0x63, 0x28, 0x61, 0x04, 0x2a,
	0x4d, 0x31, 0xd9, 0x0d, 0xdb, 0xef, 0x0e, 0xdc, 0xd1, 0x93, 0x2f, 0x1f, 0x83, 0xe3, 0x69, 0x83,
	0x68, 0xf7, 0x43, 0x5c, 0xfb, 0x66, 0xa8, 0x69, 0x77, 0x75, 0xfd, 0xce, 0x99, 0xf7, 0xb2, 0xe3,
	0x68, 0x78, 0xe9, 0x82, 0xde, 0x03, 0xbf, 0x78, 0x5f, 0xc1, 0x9b, 0x04, 0x89, 0xa5, 0x2e, 0x95,
	0xc1, 0x15, 0x44, 0xe9, 0xff, 0xb2, 0x30, 0x9c, 0x08, 0x73, 0xb0, 0x8a, 0xd7, 0x7b, 0xf0, 0xad,
	0xcd, 0xeb, 0x67, 0xff, 0x02, 0x1f, 0x0a, 0xa5, 0x09, 0x4a, 0xa1, 0x91, 0x90, 0x23, 0x2a, 0x0c,
	0x11, 0x76, 0x9f, 0x1c, 0xe9, 0x9c, 0x0a, 0xa8, 0xeb, 0x8d, 0x1f, 0xec, 0xe8, 0x7d, 0xa3, 0xff,
	0xc8, 0xd9, 0xde, 0xce, 0x2c, 0x9d, 0xd7, 0x32, 0x56, 0x7c, 0xfa, 0x6f, 0xb5, 0xf1, 0xdd, 0xf5,
	0xc6, 0x77, 0x6f, 0x36, 0xbe, 0x7b, 0xb1, 0xf5, 0x9d, 0xf5, 0xd6, 0x77, 0xae, 0xb6, 0xbe, 0xf3,
	0xf7, 0x47, 0x4e, 0xcd, 0xa2, 0x4c, 0x02, 0x2c, 0x79, 0xf8, 0xdb, 0x68, 0x82, 0x78, 0x44, 0x6d,
	0x87, 0x71, 0x7c, 0x77, 0x33, 0x85, 0x2d, 0x8f, 0xf1, 0x02, 0x51, 0x11, 0xb6, 0x97, 0x74, 0xd6,
	0xdc, 0x92, 0xa9, 0x14, 0x29, 0x92, 0xc7, 0xb6, 0x3c, 0xb9, 0x0d, 0x00, 0x00, 0xff, 0xff, 0x62,
	0x9e, 0x73, 0xaf, 0x6e, 0x02, 0x00, 0x00,
}

func (m *LiquidationsConfig) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *LiquidationsConfig) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *LiquidationsConfig) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.FillablePriceConfig.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintLiquidationsConfig(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	if m.LiquidityFeePpm != 0 {
		i = encodeVarintLiquidationsConfig(dAtA, i, uint64(m.LiquidityFeePpm))
		i--
		dAtA[i] = 0x18
	}
	if m.ValidatorFeePpm != 0 {
		i = encodeVarintLiquidationsConfig(dAtA, i, uint64(m.ValidatorFeePpm))
		i--
		dAtA[i] = 0x10
	}
	if m.InsuranceFundFeePpm != 0 {
		i = encodeVarintLiquidationsConfig(dAtA, i, uint64(m.InsuranceFundFeePpm))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *FillablePriceConfig) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *FillablePriceConfig) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *FillablePriceConfig) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.SpreadToMaintenanceMarginRatioPpm != 0 {
		i = encodeVarintLiquidationsConfig(dAtA, i, uint64(m.SpreadToMaintenanceMarginRatioPpm))
		i--
		dAtA[i] = 0x10
	}
	if m.BankruptcyAdjustmentPpm != 0 {
		i = encodeVarintLiquidationsConfig(dAtA, i, uint64(m.BankruptcyAdjustmentPpm))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintLiquidationsConfig(dAtA []byte, offset int, v uint64) int {
	offset -= sovLiquidationsConfig(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *LiquidationsConfig) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.InsuranceFundFeePpm != 0 {
		n += 1 + sovLiquidationsConfig(uint64(m.InsuranceFundFeePpm))
	}
	if m.ValidatorFeePpm != 0 {
		n += 1 + sovLiquidationsConfig(uint64(m.ValidatorFeePpm))
	}
	if m.LiquidityFeePpm != 0 {
		n += 1 + sovLiquidationsConfig(uint64(m.LiquidityFeePpm))
	}
	l = m.FillablePriceConfig.Size()
	n += 1 + l + sovLiquidationsConfig(uint64(l))
	return n
}

func (m *FillablePriceConfig) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.BankruptcyAdjustmentPpm != 0 {
		n += 1 + sovLiquidationsConfig(uint64(m.BankruptcyAdjustmentPpm))
	}
	if m.SpreadToMaintenanceMarginRatioPpm != 0 {
		n += 1 + sovLiquidationsConfig(uint64(m.SpreadToMaintenanceMarginRatioPpm))
	}
	return n
}

func sovLiquidationsConfig(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozLiquidationsConfig(x uint64) (n int) {
	return sovLiquidationsConfig(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *LiquidationsConfig) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowLiquidationsConfig
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: LiquidationsConfig: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: LiquidationsConfig: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field InsuranceFundFeePpm", wireType)
			}
			m.InsuranceFundFeePpm = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiquidationsConfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.InsuranceFundFeePpm |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValidatorFeePpm", wireType)
			}
			m.ValidatorFeePpm = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiquidationsConfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ValidatorFeePpm |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LiquidityFeePpm", wireType)
			}
			m.LiquidityFeePpm = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiquidationsConfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LiquidityFeePpm |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FillablePriceConfig", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiquidationsConfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthLiquidationsConfig
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthLiquidationsConfig
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.FillablePriceConfig.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipLiquidationsConfig(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthLiquidationsConfig
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *FillablePriceConfig) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowLiquidationsConfig
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: FillablePriceConfig: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: FillablePriceConfig: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BankruptcyAdjustmentPpm", wireType)
			}
			m.BankruptcyAdjustmentPpm = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiquidationsConfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BankruptcyAdjustmentPpm |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SpreadToMaintenanceMarginRatioPpm", wireType)
			}
			m.SpreadToMaintenanceMarginRatioPpm = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiquidationsConfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SpreadToMaintenanceMarginRatioPpm |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipLiquidationsConfig(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthLiquidationsConfig
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipLiquidationsConfig(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowLiquidationsConfig
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowLiquidationsConfig
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowLiquidationsConfig
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthLiquidationsConfig
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupLiquidationsConfig
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthLiquidationsConfig
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthLiquidationsConfig        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowLiquidationsConfig          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupLiquidationsConfig = fmt.Errorf("proto: unexpected end of group")
)
