// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: dydxprotocol/clob/mev.proto

package types

import (
	fmt "fmt"
	github_com_StreamFinance_Protocol_stream_chain_protocol_dtypes "github.com/StreamFinance-Protocol/stream-chain/protocol/dtypes"
	types "github.com/StreamFinance-Protocol/stream-chain/protocol/x/subaccounts/types"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// MEVMatch represents all necessary data to calculate MEV for a regular match.
type MEVMatch struct {
	TakerOrderSubaccountId *types.SubaccountId                                                            `protobuf:"bytes,1,opt,name=taker_order_subaccount_id,json=takerOrderSubaccountId,proto3" json:"taker_order_subaccount_id,omitempty"`
	TakerFeePpm            int32                                                                          `protobuf:"varint,2,opt,name=taker_fee_ppm,json=takerFeePpm,proto3" json:"taker_fee_ppm,omitempty"`
	MakerOrderSubaccountId *types.SubaccountId                                                            `protobuf:"bytes,3,opt,name=maker_order_subaccount_id,json=makerOrderSubaccountId,proto3" json:"maker_order_subaccount_id,omitempty"`
	MakerOrderSubticks     github_com_StreamFinance_Protocol_stream_chain_protocol_dtypes.SerializableInt `protobuf:"bytes,4,opt,name=maker_order_subticks,json=makerOrderSubticks,proto3,customtype=github.com/StreamFinance-Protocol/stream-chain/protocol/dtypes.SerializableInt" json:"maker_order_subticks"`
	MakerOrderIsBuy        bool                                                                           `protobuf:"varint,5,opt,name=maker_order_is_buy,json=makerOrderIsBuy,proto3" json:"maker_order_is_buy,omitempty"`
	MakerFeePpm            int32                                                                          `protobuf:"varint,6,opt,name=maker_fee_ppm,json=makerFeePpm,proto3" json:"maker_fee_ppm,omitempty"`
	ClobPairId             uint32                                                                         `protobuf:"varint,7,opt,name=clob_pair_id,json=clobPairId,proto3" json:"clob_pair_id,omitempty"`
	FillAmount             github_com_StreamFinance_Protocol_stream_chain_protocol_dtypes.SerializableInt `protobuf:"bytes,8,opt,name=fill_amount,json=fillAmount,proto3,customtype=github.com/StreamFinance-Protocol/stream-chain/protocol/dtypes.SerializableInt" json:"fill_amount"`
}

func (m *MEVMatch) Reset()         { *m = MEVMatch{} }
func (m *MEVMatch) String() string { return proto.CompactTextString(m) }
func (*MEVMatch) ProtoMessage()    {}
func (*MEVMatch) Descriptor() ([]byte, []int) {
	return fileDescriptor_01e0eddc304623e6, []int{0}
}
func (m *MEVMatch) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MEVMatch) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MEVMatch.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MEVMatch) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MEVMatch.Merge(m, src)
}
func (m *MEVMatch) XXX_Size() int {
	return m.Size()
}
func (m *MEVMatch) XXX_DiscardUnknown() {
	xxx_messageInfo_MEVMatch.DiscardUnknown(m)
}

var xxx_messageInfo_MEVMatch proto.InternalMessageInfo

func (m *MEVMatch) GetTakerOrderSubaccountId() *types.SubaccountId {
	if m != nil {
		return m.TakerOrderSubaccountId
	}
	return nil
}

func (m *MEVMatch) GetTakerFeePpm() int32 {
	if m != nil {
		return m.TakerFeePpm
	}
	return 0
}

func (m *MEVMatch) GetMakerOrderSubaccountId() *types.SubaccountId {
	if m != nil {
		return m.MakerOrderSubaccountId
	}
	return nil
}

func (m *MEVMatch) GetMakerOrderIsBuy() bool {
	if m != nil {
		return m.MakerOrderIsBuy
	}
	return false
}

func (m *MEVMatch) GetMakerFeePpm() int32 {
	if m != nil {
		return m.MakerFeePpm
	}
	return 0
}

func (m *MEVMatch) GetClobPairId() uint32 {
	if m != nil {
		return m.ClobPairId
	}
	return 0
}

// MEVLiquidationMatch represents all necessary data to calculate MEV for a
// liquidation.
type MEVLiquidationMatch struct {
	LiquidatedSubaccountId          types.SubaccountId                                                             `protobuf:"bytes,1,opt,name=liquidated_subaccount_id,json=liquidatedSubaccountId,proto3" json:"liquidated_subaccount_id"`
	InsuranceFundDeltaQuoteQuantums github_com_StreamFinance_Protocol_stream_chain_protocol_dtypes.SerializableInt `protobuf:"bytes,2,opt,name=insurance_fund_delta_quote_quantums,json=insuranceFundDeltaQuoteQuantums,proto3,customtype=github.com/StreamFinance-Protocol/stream-chain/protocol/dtypes.SerializableInt" json:"insurance_fund_delta_quote_quantums"`
	MakerOrderSubaccountId          types.SubaccountId                                                             `protobuf:"bytes,3,opt,name=maker_order_subaccount_id,json=makerOrderSubaccountId,proto3" json:"maker_order_subaccount_id"`
	MakerOrderSubticks              github_com_StreamFinance_Protocol_stream_chain_protocol_dtypes.SerializableInt `protobuf:"bytes,4,opt,name=maker_order_subticks,json=makerOrderSubticks,proto3,customtype=github.com/StreamFinance-Protocol/stream-chain/protocol/dtypes.SerializableInt" json:"maker_order_subticks"`
	MakerOrderIsBuy                 bool                                                                           `protobuf:"varint,5,opt,name=maker_order_is_buy,json=makerOrderIsBuy,proto3" json:"maker_order_is_buy,omitempty"`
	MakerFeePpm                     int32                                                                          `protobuf:"varint,6,opt,name=maker_fee_ppm,json=makerFeePpm,proto3" json:"maker_fee_ppm,omitempty"`
	ClobPairId                      uint32                                                                         `protobuf:"varint,7,opt,name=clob_pair_id,json=clobPairId,proto3" json:"clob_pair_id,omitempty"`
	FillAmount                      github_com_StreamFinance_Protocol_stream_chain_protocol_dtypes.SerializableInt `protobuf:"bytes,8,opt,name=fill_amount,json=fillAmount,proto3,customtype=github.com/StreamFinance-Protocol/stream-chain/protocol/dtypes.SerializableInt" json:"fill_amount"`
}

func (m *MEVLiquidationMatch) Reset()         { *m = MEVLiquidationMatch{} }
func (m *MEVLiquidationMatch) String() string { return proto.CompactTextString(m) }
func (*MEVLiquidationMatch) ProtoMessage()    {}
func (*MEVLiquidationMatch) Descriptor() ([]byte, []int) {
	return fileDescriptor_01e0eddc304623e6, []int{1}
}
func (m *MEVLiquidationMatch) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MEVLiquidationMatch) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MEVLiquidationMatch.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MEVLiquidationMatch) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MEVLiquidationMatch.Merge(m, src)
}
func (m *MEVLiquidationMatch) XXX_Size() int {
	return m.Size()
}
func (m *MEVLiquidationMatch) XXX_DiscardUnknown() {
	xxx_messageInfo_MEVLiquidationMatch.DiscardUnknown(m)
}

var xxx_messageInfo_MEVLiquidationMatch proto.InternalMessageInfo

func (m *MEVLiquidationMatch) GetLiquidatedSubaccountId() types.SubaccountId {
	if m != nil {
		return m.LiquidatedSubaccountId
	}
	return types.SubaccountId{}
}

func (m *MEVLiquidationMatch) GetMakerOrderSubaccountId() types.SubaccountId {
	if m != nil {
		return m.MakerOrderSubaccountId
	}
	return types.SubaccountId{}
}

func (m *MEVLiquidationMatch) GetMakerOrderIsBuy() bool {
	if m != nil {
		return m.MakerOrderIsBuy
	}
	return false
}

func (m *MEVLiquidationMatch) GetMakerFeePpm() int32 {
	if m != nil {
		return m.MakerFeePpm
	}
	return 0
}

func (m *MEVLiquidationMatch) GetClobPairId() uint32 {
	if m != nil {
		return m.ClobPairId
	}
	return 0
}

// ClobMidPrice contains the mid price of a CLOB pair, represented by it's ID.
type ClobMidPrice struct {
	ClobPair ClobPair                                                                       `protobuf:"bytes,1,opt,name=clob_pair,json=clobPair,proto3" json:"clob_pair"`
	Subticks github_com_StreamFinance_Protocol_stream_chain_protocol_dtypes.SerializableInt `protobuf:"bytes,2,opt,name=subticks,proto3,customtype=github.com/StreamFinance-Protocol/stream-chain/protocol/dtypes.SerializableInt" json:"subticks"`
}

func (m *ClobMidPrice) Reset()         { *m = ClobMidPrice{} }
func (m *ClobMidPrice) String() string { return proto.CompactTextString(m) }
func (*ClobMidPrice) ProtoMessage()    {}
func (*ClobMidPrice) Descriptor() ([]byte, []int) {
	return fileDescriptor_01e0eddc304623e6, []int{2}
}
func (m *ClobMidPrice) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ClobMidPrice) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ClobMidPrice.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ClobMidPrice) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClobMidPrice.Merge(m, src)
}
func (m *ClobMidPrice) XXX_Size() int {
	return m.Size()
}
func (m *ClobMidPrice) XXX_DiscardUnknown() {
	xxx_messageInfo_ClobMidPrice.DiscardUnknown(m)
}

var xxx_messageInfo_ClobMidPrice proto.InternalMessageInfo

func (m *ClobMidPrice) GetClobPair() ClobPair {
	if m != nil {
		return m.ClobPair
	}
	return ClobPair{}
}

// ValidatorMevMatches contains all matches from the validator's local
// operations queue.
type ValidatorMevMatches struct {
	Matches            []MEVMatch            `protobuf:"bytes,1,rep,name=matches,proto3" json:"matches"`
	LiquidationMatches []MEVLiquidationMatch `protobuf:"bytes,2,rep,name=liquidation_matches,json=liquidationMatches,proto3" json:"liquidation_matches"`
}

func (m *ValidatorMevMatches) Reset()         { *m = ValidatorMevMatches{} }
func (m *ValidatorMevMatches) String() string { return proto.CompactTextString(m) }
func (*ValidatorMevMatches) ProtoMessage()    {}
func (*ValidatorMevMatches) Descriptor() ([]byte, []int) {
	return fileDescriptor_01e0eddc304623e6, []int{3}
}
func (m *ValidatorMevMatches) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ValidatorMevMatches) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ValidatorMevMatches.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ValidatorMevMatches) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidatorMevMatches.Merge(m, src)
}
func (m *ValidatorMevMatches) XXX_Size() int {
	return m.Size()
}
func (m *ValidatorMevMatches) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidatorMevMatches.DiscardUnknown(m)
}

var xxx_messageInfo_ValidatorMevMatches proto.InternalMessageInfo

func (m *ValidatorMevMatches) GetMatches() []MEVMatch {
	if m != nil {
		return m.Matches
	}
	return nil
}

func (m *ValidatorMevMatches) GetLiquidationMatches() []MEVLiquidationMatch {
	if m != nil {
		return m.LiquidationMatches
	}
	return nil
}

// MevNodeToNodeMetrics is a data structure for encapsulating all MEV node <>
// node metrics.
type MevNodeToNodeMetrics struct {
	ValidatorMevMatches *ValidatorMevMatches `protobuf:"bytes,1,opt,name=validator_mev_matches,json=validatorMevMatches,proto3" json:"validator_mev_matches,omitempty"`
	ClobMidPrices       []ClobMidPrice       `protobuf:"bytes,2,rep,name=clob_mid_prices,json=clobMidPrices,proto3" json:"clob_mid_prices"`
	BpMevMatches        *ValidatorMevMatches `protobuf:"bytes,3,opt,name=bp_mev_matches,json=bpMevMatches,proto3" json:"bp_mev_matches,omitempty"`
	ProposalReceiveTime uint64               `protobuf:"varint,4,opt,name=proposal_receive_time,json=proposalReceiveTime,proto3" json:"proposal_receive_time,omitempty"`
}

func (m *MevNodeToNodeMetrics) Reset()         { *m = MevNodeToNodeMetrics{} }
func (m *MevNodeToNodeMetrics) String() string { return proto.CompactTextString(m) }
func (*MevNodeToNodeMetrics) ProtoMessage()    {}
func (*MevNodeToNodeMetrics) Descriptor() ([]byte, []int) {
	return fileDescriptor_01e0eddc304623e6, []int{4}
}
func (m *MevNodeToNodeMetrics) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MevNodeToNodeMetrics) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MevNodeToNodeMetrics.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MevNodeToNodeMetrics) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MevNodeToNodeMetrics.Merge(m, src)
}
func (m *MevNodeToNodeMetrics) XXX_Size() int {
	return m.Size()
}
func (m *MevNodeToNodeMetrics) XXX_DiscardUnknown() {
	xxx_messageInfo_MevNodeToNodeMetrics.DiscardUnknown(m)
}

var xxx_messageInfo_MevNodeToNodeMetrics proto.InternalMessageInfo

func (m *MevNodeToNodeMetrics) GetValidatorMevMatches() *ValidatorMevMatches {
	if m != nil {
		return m.ValidatorMevMatches
	}
	return nil
}

func (m *MevNodeToNodeMetrics) GetClobMidPrices() []ClobMidPrice {
	if m != nil {
		return m.ClobMidPrices
	}
	return nil
}

func (m *MevNodeToNodeMetrics) GetBpMevMatches() *ValidatorMevMatches {
	if m != nil {
		return m.BpMevMatches
	}
	return nil
}

func (m *MevNodeToNodeMetrics) GetProposalReceiveTime() uint64 {
	if m != nil {
		return m.ProposalReceiveTime
	}
	return 0
}

func init() {
	proto.RegisterType((*MEVMatch)(nil), "dydxprotocol.clob.MEVMatch")
	proto.RegisterType((*MEVLiquidationMatch)(nil), "dydxprotocol.clob.MEVLiquidationMatch")
	proto.RegisterType((*ClobMidPrice)(nil), "dydxprotocol.clob.ClobMidPrice")
	proto.RegisterType((*ValidatorMevMatches)(nil), "dydxprotocol.clob.ValidatorMevMatches")
	proto.RegisterType((*MevNodeToNodeMetrics)(nil), "dydxprotocol.clob.MevNodeToNodeMetrics")
}

func init() { proto.RegisterFile("dydxprotocol/clob/mev.proto", fileDescriptor_01e0eddc304623e6) }

var fileDescriptor_01e0eddc304623e6 = []byte{
	// 751 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xec, 0x56, 0x4d, 0x4f, 0x13, 0x41,
	0x18, 0xee, 0x42, 0x81, 0x3a, 0x14, 0x89, 0x5b, 0x20, 0x15, 0x92, 0xb6, 0xd6, 0x84, 0xd4, 0x18,
	0xb6, 0x09, 0x1e, 0x4d, 0x4c, 0x2c, 0x1f, 0x49, 0x13, 0x16, 0xcb, 0x42, 0x7a, 0x20, 0xd1, 0xc9,
	0xec, 0xee, 0xb4, 0x4c, 0xd8, 0xd9, 0x59, 0x76, 0x67, 0x2b, 0xf5, 0xec, 0xc1, 0xa3, 0x3f, 0xc2,
	0x3f, 0xe0, 0x5f, 0xd0, 0x0b, 0x47, 0x8e, 0xc6, 0x03, 0x31, 0x70, 0xf4, 0x4f, 0x98, 0xd9, 0xaf,
	0x6e, 0xa1, 0x3d, 0xa0, 0x92, 0x78, 0xf0, 0xb2, 0x99, 0x3c, 0x33, 0x7d, 0x9f, 0x8f, 0xf7, 0x9d,
	0xdd, 0x82, 0x15, 0xb3, 0x6f, 0x9e, 0x3a, 0x2e, 0xe3, 0xcc, 0x60, 0x56, 0xdd, 0xb0, 0x98, 0x5e,
	0xa7, 0xb8, 0xa7, 0x04, 0x88, 0xfc, 0x20, 0xbd, 0xa9, 0x88, 0xcd, 0xe5, 0x85, 0x2e, 0xeb, 0xb2,
	0x00, 0xaa, 0x8b, 0x55, 0x78, 0x70, 0xf9, 0xc9, 0x50, 0x15, 0xcf, 0xd7, 0x91, 0x61, 0x30, 0xdf,
	0xe6, 0x5e, 0x6a, 0x1d, 0x1d, 0x7d, 0x74, 0x93, 0x50, 0x3c, 0xa0, 0x83, 0x88, 0x1b, 0x1e, 0xa9,
	0xfe, 0xcc, 0x82, 0x9c, 0xba, 0xd5, 0x56, 0x11, 0x37, 0x8e, 0x64, 0x04, 0x1e, 0x72, 0x74, 0x8c,
	0x5d, 0xc8, 0x5c, 0x13, 0xbb, 0x70, 0x50, 0x0f, 0x12, 0xb3, 0x28, 0x55, 0xa4, 0xda, 0xec, 0xfa,
	0xaa, 0x32, 0xa4, 0x33, 0x45, 0xaf, 0xec, 0x27, 0xeb, 0xa6, 0xa9, 0x2d, 0x05, 0x85, 0x5e, 0x89,
	0x3a, 0x69, 0x5c, 0xae, 0x82, 0xb9, 0x90, 0xa2, 0x83, 0x31, 0x74, 0x1c, 0x5a, 0x9c, 0xa8, 0x48,
	0xb5, 0x29, 0x6d, 0x36, 0x00, 0xb7, 0x31, 0x6e, 0x39, 0x54, 0xc8, 0xa0, 0x63, 0x65, 0x4c, 0xde,
	0x4e, 0x06, 0x1d, 0x2d, 0xe3, 0x83, 0x04, 0x16, 0xae, 0x71, 0x70, 0x62, 0x1c, 0x7b, 0xc5, 0x6c,
	0x45, 0xaa, 0xe5, 0x1b, 0xed, 0xb3, 0x8b, 0x72, 0xe6, 0xfb, 0x45, 0x79, 0xb7, 0x4b, 0xf8, 0x91,
	0xaf, 0x2b, 0x06, 0xa3, 0xf5, 0x7d, 0xee, 0x62, 0x44, 0xb7, 0x89, 0x8d, 0x6c, 0x03, 0xaf, 0xb5,
	0x92, 0x06, 0x04, 0xf0, 0x9a, 0x71, 0x84, 0x88, 0x5d, 0x4f, 0xb2, 0x36, 0x79, 0xdf, 0xc1, 0x9e,
	0xb2, 0x8f, 0x5d, 0x82, 0x2c, 0xf2, 0x0e, 0xe9, 0x16, 0x6e, 0xda, 0x5c, 0x93, 0x87, 0xe4, 0x04,
	0x8c, 0xf2, 0x53, 0x20, 0xa7, 0x95, 0x10, 0x0f, 0xea, 0x7e, 0xbf, 0x38, 0x55, 0x91, 0x6a, 0x39,
	0x6d, 0x7e, 0x70, 0xbe, 0xe9, 0x35, 0xfc, 0xbe, 0x88, 0x8f, 0x0e, 0xc5, 0x37, 0x1d, 0xc6, 0x47,
	0x53, 0xf1, 0x55, 0x40, 0x3e, 0xe9, 0xb2, 0x48, 0x6c, 0xa6, 0x22, 0xd5, 0xe6, 0x34, 0x20, 0xb0,
	0x16, 0x22, 0x6e, 0xd3, 0x94, 0xdf, 0x82, 0xd9, 0x0e, 0xb1, 0x2c, 0x88, 0xa8, 0x88, 0xa3, 0x98,
	0xbb, 0x53, 0xcf, 0x40, 0x50, 0xbd, 0x0c, 0x98, 0xaa, 0xef, 0xa7, 0x41, 0x41, 0xdd, 0x6a, 0xef,
	0x90, 0x13, 0x9f, 0x98, 0x88, 0x13, 0x66, 0x87, 0x83, 0xd7, 0x01, 0x45, 0x2b, 0xc2, 0xb0, 0xf9,
	0x27, 0x73, 0xd7, 0xc8, 0x0a, 0x17, 0xda, 0xd2, 0xa0, 0xda, 0x50, 0xdb, 0x3f, 0x49, 0xe0, 0x31,
	0xb1, 0x3d, 0xdf, 0x15, 0x7e, 0x60, 0xc7, 0xb7, 0x4d, 0x68, 0x62, 0x8b, 0x23, 0x78, 0xe2, 0x33,
	0x8e, 0xe1, 0x89, 0x8f, 0x6c, 0xee, 0x53, 0x2f, 0x18, 0xca, 0xbb, 0x4b, 0xa4, 0x9c, 0x48, 0xd8,
	0xf6, 0x6d, 0x73, 0x53, 0x08, 0xd8, 0x13, 0xfc, 0x7b, 0x11, 0xbd, 0xdc, 0xfd, 0x6b, 0x17, 0x20,
	0xce, 0xe3, 0xff, 0x35, 0xf8, 0x97, 0xae, 0xc1, 0x17, 0x09, 0xe4, 0x37, 0x2c, 0xa6, 0xab, 0xc4,
	0x6c, 0xb9, 0xc4, 0xc0, 0xf2, 0x0b, 0x70, 0x2f, 0xd1, 0x1a, 0x0d, 0xfc, 0x8a, 0x72, 0xe3, 0x83,
	0xa0, 0x6c, 0x44, 0xda, 0xa3, 0xae, 0xe6, 0x62, 0x2f, 0xb2, 0x0b, 0x72, 0x49, 0xeb, 0xee, 0x76,
	0x76, 0x13, 0x9e, 0xea, 0x67, 0x09, 0x14, 0xda, 0xc8, 0x12, 0xb7, 0x8c, 0xb9, 0x2a, 0xee, 0x05,
	0x37, 0x19, 0x7b, 0xf2, 0x73, 0x30, 0x43, 0xc3, 0x65, 0x51, 0xaa, 0x4c, 0x8e, 0x71, 0x12, 0x7f,
	0x72, 0x22, 0x27, 0xf1, 0x2f, 0xe4, 0xd7, 0xa0, 0x60, 0x0d, 0x5e, 0x0e, 0x30, 0x2e, 0x34, 0x11,
	0x14, 0x5a, 0x1d, 0x5d, 0xe8, 0xfa, 0xdb, 0x24, 0xaa, 0x29, 0x5b, 0xd7, 0x70, 0xec, 0x55, 0xbf,
	0x4e, 0x80, 0x05, 0x15, 0xf7, 0x76, 0x99, 0x89, 0x0f, 0x98, 0x78, 0xaa, 0x98, 0xbb, 0xc4, 0xf0,
	0xe4, 0x43, 0xb0, 0xd8, 0x8b, 0xbd, 0x40, 0x8a, 0x7b, 0x70, 0x60, 0x41, 0x1a, 0xc3, 0x3c, 0xc2,
	0xbb, 0x56, 0xe8, 0x8d, 0x08, 0x44, 0x05, 0xf3, 0x41, 0x73, 0x29, 0x31, 0xa1, 0x23, 0xda, 0x1d,
	0xfb, 0x29, 0x8f, 0x69, 0x71, 0x3c, 0x16, 0x91, 0x91, 0x39, 0x23, 0x85, 0x79, 0xf2, 0x0e, 0xb8,
	0xaf, 0x3b, 0x43, 0x1a, 0x27, 0x6f, 0xa5, 0x31, 0xaf, 0x3b, 0x29, 0x71, 0xeb, 0x60, 0xd1, 0x71,
	0x99, 0xc3, 0x3c, 0x64, 0x41, 0x17, 0x1b, 0x98, 0xf4, 0x30, 0xe4, 0x84, 0xe2, 0xe0, 0x0d, 0x90,
	0xd5, 0x0a, 0xf1, 0xa6, 0x16, 0xee, 0x1d, 0x10, 0x8a, 0x1b, 0x6f, 0xce, 0x2e, 0x4b, 0xd2, 0xf9,
	0x65, 0x49, 0xfa, 0x71, 0x59, 0x92, 0x3e, 0x5e, 0x95, 0x32, 0xe7, 0x57, 0xa5, 0xcc, 0xb7, 0xab,
	0x52, 0xe6, 0x70, 0xf3, 0x77, 0xa7, 0xed, 0x34, 0xfc, 0x77, 0x12, 0xcc, 0x9c, 0x3e, 0x1d, 0xc0,
	0xcf, 0x7e, 0x05, 0x00, 0x00, 0xff, 0xff, 0xcf, 0xce, 0xa4, 0x04, 0x30, 0x09, 0x00, 0x00,
}

func (m *MEVMatch) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MEVMatch) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MEVMatch) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.FillAmount.Size()
		i -= size
		if _, err := m.FillAmount.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintMev(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x42
	if m.ClobPairId != 0 {
		i = encodeVarintMev(dAtA, i, uint64(m.ClobPairId))
		i--
		dAtA[i] = 0x38
	}
	if m.MakerFeePpm != 0 {
		i = encodeVarintMev(dAtA, i, uint64(m.MakerFeePpm))
		i--
		dAtA[i] = 0x30
	}
	if m.MakerOrderIsBuy {
		i--
		if m.MakerOrderIsBuy {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x28
	}
	{
		size := m.MakerOrderSubticks.Size()
		i -= size
		if _, err := m.MakerOrderSubticks.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintMev(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	if m.MakerOrderSubaccountId != nil {
		{
			size, err := m.MakerOrderSubaccountId.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintMev(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if m.TakerFeePpm != 0 {
		i = encodeVarintMev(dAtA, i, uint64(m.TakerFeePpm))
		i--
		dAtA[i] = 0x10
	}
	if m.TakerOrderSubaccountId != nil {
		{
			size, err := m.TakerOrderSubaccountId.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintMev(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MEVLiquidationMatch) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MEVLiquidationMatch) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MEVLiquidationMatch) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.FillAmount.Size()
		i -= size
		if _, err := m.FillAmount.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintMev(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x42
	if m.ClobPairId != 0 {
		i = encodeVarintMev(dAtA, i, uint64(m.ClobPairId))
		i--
		dAtA[i] = 0x38
	}
	if m.MakerFeePpm != 0 {
		i = encodeVarintMev(dAtA, i, uint64(m.MakerFeePpm))
		i--
		dAtA[i] = 0x30
	}
	if m.MakerOrderIsBuy {
		i--
		if m.MakerOrderIsBuy {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x28
	}
	{
		size := m.MakerOrderSubticks.Size()
		i -= size
		if _, err := m.MakerOrderSubticks.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintMev(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	{
		size, err := m.MakerOrderSubaccountId.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintMev(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	{
		size := m.InsuranceFundDeltaQuoteQuantums.Size()
		i -= size
		if _, err := m.InsuranceFundDeltaQuoteQuantums.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintMev(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	{
		size, err := m.LiquidatedSubaccountId.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintMev(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *ClobMidPrice) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ClobMidPrice) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ClobMidPrice) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.Subticks.Size()
		i -= size
		if _, err := m.Subticks.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintMev(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	{
		size, err := m.ClobPair.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintMev(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *ValidatorMevMatches) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ValidatorMevMatches) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ValidatorMevMatches) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.LiquidationMatches) > 0 {
		for iNdEx := len(m.LiquidationMatches) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.LiquidationMatches[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintMev(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.Matches) > 0 {
		for iNdEx := len(m.Matches) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Matches[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintMev(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *MevNodeToNodeMetrics) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MevNodeToNodeMetrics) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MevNodeToNodeMetrics) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ProposalReceiveTime != 0 {
		i = encodeVarintMev(dAtA, i, uint64(m.ProposalReceiveTime))
		i--
		dAtA[i] = 0x20
	}
	if m.BpMevMatches != nil {
		{
			size, err := m.BpMevMatches.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintMev(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if len(m.ClobMidPrices) > 0 {
		for iNdEx := len(m.ClobMidPrices) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.ClobMidPrices[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintMev(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if m.ValidatorMevMatches != nil {
		{
			size, err := m.ValidatorMevMatches.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintMev(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintMev(dAtA []byte, offset int, v uint64) int {
	offset -= sovMev(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MEVMatch) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.TakerOrderSubaccountId != nil {
		l = m.TakerOrderSubaccountId.Size()
		n += 1 + l + sovMev(uint64(l))
	}
	if m.TakerFeePpm != 0 {
		n += 1 + sovMev(uint64(m.TakerFeePpm))
	}
	if m.MakerOrderSubaccountId != nil {
		l = m.MakerOrderSubaccountId.Size()
		n += 1 + l + sovMev(uint64(l))
	}
	l = m.MakerOrderSubticks.Size()
	n += 1 + l + sovMev(uint64(l))
	if m.MakerOrderIsBuy {
		n += 2
	}
	if m.MakerFeePpm != 0 {
		n += 1 + sovMev(uint64(m.MakerFeePpm))
	}
	if m.ClobPairId != 0 {
		n += 1 + sovMev(uint64(m.ClobPairId))
	}
	l = m.FillAmount.Size()
	n += 1 + l + sovMev(uint64(l))
	return n
}

func (m *MEVLiquidationMatch) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.LiquidatedSubaccountId.Size()
	n += 1 + l + sovMev(uint64(l))
	l = m.InsuranceFundDeltaQuoteQuantums.Size()
	n += 1 + l + sovMev(uint64(l))
	l = m.MakerOrderSubaccountId.Size()
	n += 1 + l + sovMev(uint64(l))
	l = m.MakerOrderSubticks.Size()
	n += 1 + l + sovMev(uint64(l))
	if m.MakerOrderIsBuy {
		n += 2
	}
	if m.MakerFeePpm != 0 {
		n += 1 + sovMev(uint64(m.MakerFeePpm))
	}
	if m.ClobPairId != 0 {
		n += 1 + sovMev(uint64(m.ClobPairId))
	}
	l = m.FillAmount.Size()
	n += 1 + l + sovMev(uint64(l))
	return n
}

func (m *ClobMidPrice) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.ClobPair.Size()
	n += 1 + l + sovMev(uint64(l))
	l = m.Subticks.Size()
	n += 1 + l + sovMev(uint64(l))
	return n
}

func (m *ValidatorMevMatches) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Matches) > 0 {
		for _, e := range m.Matches {
			l = e.Size()
			n += 1 + l + sovMev(uint64(l))
		}
	}
	if len(m.LiquidationMatches) > 0 {
		for _, e := range m.LiquidationMatches {
			l = e.Size()
			n += 1 + l + sovMev(uint64(l))
		}
	}
	return n
}

func (m *MevNodeToNodeMetrics) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ValidatorMevMatches != nil {
		l = m.ValidatorMevMatches.Size()
		n += 1 + l + sovMev(uint64(l))
	}
	if len(m.ClobMidPrices) > 0 {
		for _, e := range m.ClobMidPrices {
			l = e.Size()
			n += 1 + l + sovMev(uint64(l))
		}
	}
	if m.BpMevMatches != nil {
		l = m.BpMevMatches.Size()
		n += 1 + l + sovMev(uint64(l))
	}
	if m.ProposalReceiveTime != 0 {
		n += 1 + sovMev(uint64(m.ProposalReceiveTime))
	}
	return n
}

func sovMev(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozMev(x uint64) (n int) {
	return sovMev(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MEVMatch) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMev
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MEVMatch: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MEVMatch: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TakerOrderSubaccountId", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMev
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMev
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMev
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.TakerOrderSubaccountId == nil {
				m.TakerOrderSubaccountId = &types.SubaccountId{}
			}
			if err := m.TakerOrderSubaccountId.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TakerFeePpm", wireType)
			}
			m.TakerFeePpm = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMev
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TakerFeePpm |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MakerOrderSubaccountId", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMev
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMev
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMev
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.MakerOrderSubaccountId == nil {
				m.MakerOrderSubaccountId = &types.SubaccountId{}
			}
			if err := m.MakerOrderSubaccountId.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MakerOrderSubticks", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMev
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthMev
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthMev
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MakerOrderSubticks.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MakerOrderIsBuy", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMev
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.MakerOrderIsBuy = bool(v != 0)
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MakerFeePpm", wireType)
			}
			m.MakerFeePpm = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMev
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MakerFeePpm |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ClobPairId", wireType)
			}
			m.ClobPairId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMev
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ClobPairId |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FillAmount", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMev
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthMev
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthMev
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.FillAmount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMev(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMev
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MEVLiquidationMatch) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMev
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MEVLiquidationMatch: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MEVLiquidationMatch: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LiquidatedSubaccountId", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMev
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMev
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMev
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.LiquidatedSubaccountId.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field InsuranceFundDeltaQuoteQuantums", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMev
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthMev
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthMev
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.InsuranceFundDeltaQuoteQuantums.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MakerOrderSubaccountId", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMev
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMev
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMev
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MakerOrderSubaccountId.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MakerOrderSubticks", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMev
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthMev
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthMev
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MakerOrderSubticks.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MakerOrderIsBuy", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMev
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.MakerOrderIsBuy = bool(v != 0)
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MakerFeePpm", wireType)
			}
			m.MakerFeePpm = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMev
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MakerFeePpm |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ClobPairId", wireType)
			}
			m.ClobPairId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMev
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ClobPairId |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FillAmount", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMev
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthMev
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthMev
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.FillAmount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMev(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMev
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ClobMidPrice) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMev
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ClobMidPrice: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ClobMidPrice: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ClobPair", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMev
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMev
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMev
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ClobPair.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Subticks", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMev
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthMev
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthMev
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Subticks.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMev(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMev
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ValidatorMevMatches) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMev
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ValidatorMevMatches: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ValidatorMevMatches: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Matches", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMev
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMev
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMev
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Matches = append(m.Matches, MEVMatch{})
			if err := m.Matches[len(m.Matches)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LiquidationMatches", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMev
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMev
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMev
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.LiquidationMatches = append(m.LiquidationMatches, MEVLiquidationMatch{})
			if err := m.LiquidationMatches[len(m.LiquidationMatches)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMev(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMev
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MevNodeToNodeMetrics) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMev
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MevNodeToNodeMetrics: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MevNodeToNodeMetrics: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValidatorMevMatches", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMev
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMev
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMev
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.ValidatorMevMatches == nil {
				m.ValidatorMevMatches = &ValidatorMevMatches{}
			}
			if err := m.ValidatorMevMatches.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ClobMidPrices", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMev
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMev
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMev
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ClobMidPrices = append(m.ClobMidPrices, ClobMidPrice{})
			if err := m.ClobMidPrices[len(m.ClobMidPrices)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BpMevMatches", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMev
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMev
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMev
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.BpMevMatches == nil {
				m.BpMevMatches = &ValidatorMevMatches{}
			}
			if err := m.BpMevMatches.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProposalReceiveTime", wireType)
			}
			m.ProposalReceiveTime = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMev
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ProposalReceiveTime |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipMev(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMev
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipMev(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowMev
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMev
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMev
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthMev
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupMev
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthMev
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthMev        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowMev          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupMev = fmt.Errorf("proto: unexpected end of group")
)
